### ISSUE TITLE
Add information and links for Nightly to channel page

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#102]
I suggest we add Nightly build info to https://www.thunderbird.net/en-US/channel/ like firefox has done at https://www.mozilla.org/en-US/firefox/channel/desktop/ - with appropriate cautionary language of course.

And then link to the channel page from  https://www.thunderbird.net/en-US/get-involved/ l

ref: issue 42

**Comment by mkmelin** [comment]
Agreed. Why is it channel, and not channels?

**Comment by wsmwk** [comment]
Dunno.  Speculation - when the page started perhaps a decade ago, they only offered beta.

**Comment by Sancus** [comment]
The page was never called 'channel', that's just the url slug. It originally had Earlybird and Beta on it and was called "Future Releases", then eventually became "Releases", and then when I removed Earlybird from it I just changed the name to "Beta".

I figured we were going to add Nightly to this page already when Alessandro redesigns it. Unless the redesign doesn't happen for like 6+ months or something.

I do still think it is questionable to encourage the average user to run Nightly given the fact that it can put so much data at risk.

**Comment by Sancus** [comment]
@wsmwk @mkmelin https://www-new.thunderbird.net/en-US/

So the new website doesn't have a channel page, instead Beta is on the front page at the bottom. Should we add Nightly in a box next to it? 

I am a bit concerned about making Nightly too easy to download but honestly maybe I'm overly concerned about that. If the text says it's an unstable development version that can eat your data, and people don't read it, that's going to happen no matter where we put the text or the button.

**Comment by Alecaddd** [comment]
I'm thinking about having a small tab in the Beta box, so the user can switch between beta and nightly channel. In that way we don't destroy the layout with an extra box/button, we have the space for a proper warning text, and we sort of "hide" nightly behind a click.

**Comment by mkmelin** [comment]
I'd not be too concerned about adding nightly. If you're willing to hep and actively give feedback, that's where you want to be.

**Comment by Sancus** [comment]
This is fixed on the redesign.
