### ISSUE TITLE
Add Add-ons Mailing lists to Communication Links

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#108]
We have an generic [add-ons list](https://thunderbird.topicbox.com/groups/addons) and [add-ons reviewers list](tb-addon-reviewers@lists.thunderbird.net).

They should be added at the bottom of the get involved page along with the other lists.

**Comment by RCMainak** [comment]
@ryanleesipes I would love to work on this issue. I noticed the second link you provided is not valid. Can you please provide the correct url.

**Comment by ryanleesipes** [comment]
@RCMainak it should be a a mailto link since it is not a mailing list someone can join (they can only send email to it).

So mailto:tb-addon-reviewers@lists.thunderbird.net

**Comment by Sancus** [comment]
@ryanleesipes Adding the reviewer list onto the website could mean that it will start receiving spam. Is it moderated? Are you prepared for that?

**Comment by kewisch** [comment]
The reviewers list is meant for internal discussion, at least the AMO one. I'd recommend against and instead have a dev-addons equivalent or so. Maybe an amo-admins equivalent

**Comment by ryanleesipes** [comment]
If we are worried about spam, I am okay with omitting that mailing list. I believe people who submit their add-ons to ATN are informed of the mailing list.
