### ISSUE TITLE
fix css alignment on org page

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#11]

**Comment by hawkinsjames** [comment]
I believe I've fixed the alignment for the content section on this page by adding a margin that matches the above feature section. I added the new css to the **organizations.less** file. I just want to make sure this is what you were asking for, so please let me know if I'm on the right track. 

Updated
![thunderbird-org-fixed-screenshot](https://user-images.githubusercontent.com/19354835/36984568-326c24de-2063-11e8-944a-87294c9d3d96.png)

Original
![thunderbird-org-original-screenshot](https://user-images.githubusercontent.com/19354835/36984943-ff452bea-2063-11e8-910c-e50d2d256f2a.png)

**Comment by Sancus** [comment]
Yeah that looks like the issue I was referring to when I filed this. You can pull request that.

**Comment by hawkinsjames** [comment]
Okay, I forked the repo, made the changes and created a pull request. Hopefully I did it right!

**Comment by Sancus** [comment]
Fixed in e979c6074d9c2562ce1e5f2be878dad20281c563
