### ISSUE TITLE
[New Section] Work with Us

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/thunderbird-website#113]
As I'm working on the new version of the website, Magnus suggested to implement a page where we can list open positions and job opportunities.

I'm opening this bug to kick-off the discussion and start drafting some content and how much importance we want to give to this page.

**Comment by Sancus** [comment]
Do we use a Mozilla Foundation back-end to post positions? Is there an API we can pull from?

Ideally, we don't want to have to update multiple things when we fill a position or post a new one.

cc @ryanleesipes

**Comment by ryanleesipes** [comment]
At the moment we don't. We are considering greenhouse.io

I don't think we can plan for using that in v1, but I would plan to update the page to pull from them or another similar service.

**Comment by Alecaddd** [comment]
Fixed by #165
