### ISSUE TITLE
[macOS] python build-site.py --watch stops after a few minutes

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/thunderbird-website#114]
The command `python build-site.py --enus --watch` works and watches for changes for a few minutes before turning unresponsive.
This seems to be random and I can't figure out what's causing it, also because no error or local server failure it's shown.
It simply stops refreshing the assets or recognizing any changes when files are saved.

**Comment by Sancus** [comment]
I assume this is on MacOS? I cannot reproduce it on CentOS. It runs just fine for 45+ minutes. My guess is somehow the observer thread is dying or being killed somehow. There should be two threads active while this is running.

The code for this is [just boilerplate for the mostpart](https://github.com/thundernest/thunderbird-website/blob/master/builder.py#L333), it's all [the Watchdog library](https://github.com/gorakhargosh/watchdog/issues). I did some googling and couldn't find anything really apart from some talk about network drives disconnecting causing observer threads to fail.

**Comment by Alecaddd** [comment]
Thanks for the info, and yes, it's macOS.
I'll keep this issue open and try to troubleshoot it if I have some free time.

**Comment by Alecaddd** [comment]
This seems to have been solved for me with the latest python update.
Closing it.
