### ISSUE TITLE
Add documentation about where to get latest build ppa

### ISSUE THREAD

**Issue by COLABORATI** [thundernest/thunderbird-website#12]
I just read that Thunderbird 54 supports matrix.org - but I can not find a way to install it on Ubuntu 16.04. The website does not provide any hint about a way to install newer releases. I can find lots of (outdated) information about several ppa and other sources, but I would like to read that kind of info on the official thunderbird site.

Thank you very much for your attention!

**Comment by Sancus** [comment]
I honestly have no idea what this is about. Thunderbird ppa just brings up https://launchpad.net/~mozillateam/+archive/ubuntu/thunderbird-next

I suspect if there is some need for documentation here it should be on the wiki.

@jorgk3 @kewisch Any ideas?

**Comment by kewisch** [comment]
As the ppa builds are third party, I don't believe we should be advertising them. Providing updates via distro installs is up to the package maintainers. You are welcome to download the official package from mozilla.org and run it from a folder.

**Comment by wsmwk** [comment]
OTOH, these types of questions inevitably bubble up to support venues and what not. (And I'm sure coming soon to discourse too.)

As an alternative, can we point linux users who want a distro provided build to a Thunderbird wiki type page where links to distro sites could be easily maintained by both distros and thunderbird support?
