### ISSUE TITLE
Update site with 32 & 64bit links. Msi links. Group Policy files

### ISSUE THREAD

**Issue by Solwayuk** [thundernest/thunderbird-website#124]
Now version 68 has been released.
The site needs a quick update to link to the installers. And other documentation. 

See the ftp site for exe files. 
32bit and 64bit icons need adding to the download page on all languages. 

May I suggest a drop down list box in order to select 32/64bit, language and exe/msi files.? 
like this... https://www.mozilla.org/en-GB/firefox/all/#product-desktop-release

**In the organisation page**
www.thunderbird.net/en-US/organizations

The msi installers need links. For example
https://archive.mozilla.org/pub/thunderbird/releases/68.0/win64/en-US/Thunderbird%20Setup%2068.0.msi

And there is no group Policy admx files found anywhere! Although mentioned in the change log of v68. A link needs to be provided. 
Plus documentation on the gpo settings.

The old enterprise pages and wiki's could do with a complete overhaul/delete and relevant docs added to thunderbird.Net, it's a mess

**Comment by Sancus** [comment]
I believe group policy documentation and links belong on the support wiki, [similarly to Firefox](https://support.mozilla.org/en-US/kb/customizing-firefox-using-group-policy-windows), not on the website.

@wsmwk Is there some place to file a bug for adding a SUMO document?

**Comment by Sancus** [comment]
64-bit links are added, and there is [already an issue](https://github.com/thundernest/thunderbird-website/issues/85) for the MSI links here.

Further improvements to the Organization page will arrive with the website redesign in a few weeks.
