### ISSUE TITLE
the release notes page for 60.9.0 isn't published/available

### ISSUE THREAD

**Issue by Nono-m0le** [thundernest/thunderbird-website#125]
It seems that the release notes page for Thunderbird 60.9.0 isn't available: https://www.thunderbird.net/en-US/thunderbird/60.9.0/releasenotes/

**Comment by Sancus** [comment]
https://www.thunderbird.net/en-US/thunderbird/60.9.0/releasenotes/

This is fixed now. Note that this may be updated in the future, I'm not sure if these were finalized, but a working page is better than a 404...

Thanks for the report.
