### ISSUE TITLE
Thunderbird Add-on "Folder Account" not working properly in newer versions(68.1 and up)

### ISSUE THREAD

**Issue by dave1039** [thundernest/thunderbird-website#131]
Thunderbird's add-on folder account does not work correctly. When right clicking on a folder and going into properties in the General Information tab there is an option at the bottom that let's you choose from what account you would like to send the email from (From Account). When clicking on this and changing to the right one then clicking OK it seems to stick, but then when you go back into folder options it's changed right back to "Use Default."

**Comment by MadMattAu** [comment]
That does not sound like anything to do with the web site.  Perhaps make a support request to the author of the add-on..  The support email is on the download page https://addons.thunderbird.net/en-US/thunderbird/addon/folder-account/

You might consider making an issue report in the git hub project https://github.com/eykamp/Folder-Account/issues

But be aware that the download page says the author is no longer supporting the add-on.  So I guess you will have to fix it yourself.

**Comment by Sancus** [comment]
As above, addons are the responsibility of the individual author, and nothing to do with Thunderbird or the Thunderbird website.
