### ISSUE TITLE
Fix release notes internal links, or remove them

### ISSUE THREAD

**Issue by MadMattAu** [thundernest/thunderbird-website#132]
Release notes have a link stating "Look at the known issues list and see if we already know about the problem"  the link links to the text immediately to the left of the link on the same page.  This is just a poor user experience.  There are thousands of bugs filed and we list two "known issues"

**Comment by Sancus** [comment]
I don't really agree? The known issues list is for things that are commonly hit or high profile enough that if people started reporting them, it would just needlessly spam Bugzilla. So it's reasonable to suggest people take a look at that part of the page before filing a bug, and on some release notes pages, the known issues list is quite far down, so linking to it works well.

For every other bug, Bugzilla has an existing flow to show you existing bugs that might be similar to what you're reporting, there's no need for us to try to force it onto the release notes page.

I'm inclined to WONTFIX this, but I'll leave it open for a bit unless someone else has some kind of persuasive argument.
