### ISSUE TITLE
System Requirements Link on the Installing Thunderbird on Mac page

### ISSUE THREAD

**Issue by brLouis** [thundernest/thunderbird-website#137]
Clicking the link on this page takes you to https://www.thunderbird.net/en-US/thunderbird/latest/system-requirements/  where it says "There's Nothing Here."

**Comment by Sancus** [comment]
This is fixed now. Thanks for the report. The document in question has been updated, and the original link(https://www.mozilla.org/thunderbird/latest/system-requirements/) has a rewrite in case anyone else is using it.
