### ISSUE TITLE
Personas and lightweight "skins" should be changed to simply Themes

### ISSUE THREAD

**Issue by Paenglab** [thundernest/thunderbird-website#139]
The new Thunderbird page uses

`With Extensions, Personas, lightweight "skins”, and many more features you can change the look and feel of Thunderbird in an instant. `

Personas and lightweight "skins" are old names. I think it's better to simply use

`With Extensions, Themes, and many more features you can change the look and feel of Thunderbird in an instant. `

**Comment by Alecaddd** [comment]
Great, thanks for bringing this up.
@ryanleesipes, can you take care of this?

**Comment by Sancus** [comment]
Where do you see this text? https://www-new.thunderbird.net/en-US/features/
I only see:

> Thunderbird Look & Feel
> 
> Themes allow you to change the look of Thunderbird in an instant. Working on getting to inbox zero at night? Turn on the dark theme to make managing your email easier on the eyes. Thunderbird ships with both light and dark themes, and more are available as add-ons.

**Comment by Paenglab** [comment]
On https://www-new.thunderbird.net/en-US/ under "FULLY CUSTOMIZABLE".

**Comment by Sancus** [comment]
Ah gotcha, I'm blind haha. Yeah that should probably be more similar to the text on the Features page.
