### ISSUE TITLE
Make "Support" link to SUMO Site

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#14]
Right now when I click on the "Support" link at the top-right corner of the page it goes nowhere, perhaps we should point it here? https://support.mozilla.org/en-US/questions/thunderbird

**Comment by Sancus** [comment]
This only happens on mobile-sized layouts. Can be replicated on desktop by shrinking your window enough. This is minor since mobile traffic to the website is negligible, but will get to this in February.

**Comment by ryanleesipes** [comment]
Let me know if you have any luck with this @Sancus  - it affects me on Linux desktop using Firefox 59 as well as on mobile.

**Comment by Sancus** [comment]
This took a ridiculous amount of time but it should be fixed now. Tested on Windows desktop Firefox with responsive layout, and on Galaxy S8 Android Chrome.
