### ISSUE TITLE
nightly channel points to tb 54

### ISSUE THREAD

**Issue by mkmelin** [thundernest/thunderbird-website#143]
On the new website, clicking the nightly channel, it points to a really ancient Thunderbird

https://download.mozilla.org/?product=thunderbird-54.0a2-SSL&os=linux64&lang=en-US

Also, "Systems and languages" points to non-existent https://www-new.thunderbird.net/en-US/thunderbird/alpha/all/

**Comment by Sancus** [comment]
Yeah I don't think we can even have systems & languages for nightly at all, because there's no metadata for that on product-details.

I'll just remove it.

**Comment by Sancus** [comment]
Fixed by #147.
