### ISSUE TITLE
Organizations page verbiage is confusing

### ISSUE THREAD

**Issue by mkmelin** [thundernest/thunderbird-website#144]
https://www-new.thunderbird.net/en-US/organizations/

Currently says: "A community-led project that allows organizations to benefit from the speed, flexibility and security of Thunderbird while getting the support they need. "

This is confusing: Thunderbird only do ESR releases (other than betas). 

"The Thunderbird Extended Support Releases (ESR) are mainstream releases, operating similarly to Mozilla Firefox ESR. They are stable for approximately one year before receiving feature updates. "

The mainstream releases ARE the ESR releases, not the other way around. It's NOT operating similarly to the Firefox ESR.

**Comment by Sancus** [comment]
Agreed, I'll see if I can rewrite this to something that makes more sense.
