### ISSUE TITLE
thunderbird logo badly visible - add white shadow?

### ISSUE THREAD

**Issue by RealRaven2000** [thundernest/thunderbird-website#146]
love the new Thunderbird page, but the small logo should have an outline or white shadow to sufficiently be seen in front of a blue background. I tried adding
box-shadow: 2px 2px 5px 4px rgba(255,255,255,0.9);
to various elements around this, but I do not understand the markup - there are a ton of "path" elements here, is the icon an svg graphic? I didn't find a rule for the actual icon...

**Comment by Sancus** [comment]
Yes, it is an svg, and it includes the words "Thunderbird" because that's the trademark. I think the visibility is fine and adding a shadow just to the icon would require editing the graphic.

Anyways I'll leave this up to Alessandro.

**Comment by Alecaddd** [comment]
This is a wontfix for me.
The visibility of the logo is fine, the only areas where it blends a bit with the background are the edges of the left wing, which is not a big deal at all. The logo is visible and recognizable, and it's also repeat in the page.
Also, adding drop shadow to the logo is a general red flag as it changes the established brand identity.

**Comment by Sancus** [comment]
Agreed, thanks.
