### ISSUE TITLE
Documentation heading  link does not mention SUMO

### ISSUE THREAD

**Issue by MadMattAu** [thundernest/thunderbird-website#149]
https://www-new.thunderbird.net/en-US/get-involved/

SUMO has been the home of Thunderbirds user facing documentation for more than 5 years.  Perhaps it can be linked to from this part of the web site, instead of the mozila wiki that has extremely limited exposure in user facing situations.

**Comment by Sancus** [comment]
That's really because that section is focused on developer documentation, not user documentation. But I agree user documentation is an important area of contribution, and so we should redo this section so it talks about documentation both 'for users' and 'for developers'.

**Comment by Sancus** [comment]
This was actually fixed some time ago, the Documentation section now separately mentions user docs on SUMO and developer docs on DTN. https://github.com/thundernest/thunderbird-website/commit/718c64768a0549032202e4a17eb3bb46bc4da472#diff-fb6547ef84bd0a25cb48b46ee96e985f63a3d62613d089b440e8711a251da421

https://www.thunderbird.net/en-US/get-involved/#documentation
