### ISSUE TITLE
Load Assets?

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#15]
When I build and open up the index.html in thunderbird.net (for the website), it loads without assets! Is there anyway to fix this?

**Comment by ryanleesipes** [comment]
Not just assets, I guess it's CSS formatting too.

**Comment by Sancus** [comment]
That's normal, it's not built with local paths, it's built to be hosted by a web server. I do development in a VM running apache.

I don't think it's worth independently fixing this, should probably be solved with a docker container.

**Comment by benbucksch** [comment]
Ryan, you can just start Python's "Simple HTTP server", using:
```
cd <your/directory/with/the/index.html>
python -m SimpleHTTPServer 8000
```
and then open `http://localhost:8000` in your browser.

**Comment by Sancus** [comment]
Ah yeah good point thanks Ben, I always forget about that thing.

It'll be a little janky because it won't run the language redirect code and stuff but it does indeed load individual pages with assets just fine.

**Comment by benbucksch** [comment]
Yeah, it's a really simple and useful tool for small stuff.

**Comment by ryanleesipes** [comment]
@benbucksch sorry to hit this again, what directory do you run the simple http server in. It still complains about css issues even though I have less installed globally (the specific version outlined in #20) and everything builds without error. I'm clearly doing something wrong, but I can't determine what that is.

**Comment by ryanleesipes** [comment]
Nevermind, I figured it out, I had to run it in the thunderbird.net directory, I can't believe I didn't try that sooner, I was going into the en-US directory and running it since that's where my index.html file is.
