### ISSUE TITLE
Redesigned Release notes page doesn't support group headers for Beta

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#151]
https://www-new.thunderbird.net/en-US/thunderbird/71.0beta/releasenotes/

The release notes format supports multiple groups of notes with a heading, which is mostly used for consecutive beta versions as on the live page: https://www.thunderbird.net/en-US/thunderbird/71.0beta/releasenotes/

Unfortunately, it seems like we forgot about that on the redesigned template so it looks completely broken right now. It needs support for those group headings.

**Comment by Alecaddd** [comment]
Argh, sorry I missed that.
I'll take care of it.
