### ISSUE TITLE
Translation error in french version

### ISSUE THREAD

**Issue by HumanG33k** [thundernest/thunderbird-website#156]
There is an error in french version translation (main page) :
```
Thunderbird est financé pas des utilisateurs comme vous
```
should be 
```
Thunderbird est financé par des utilisateurs comme vous
```
pas = not 
par = by 

thx to Goldocrack in irc.

**Comment by Sancus** [comment]
I added this suggestion on Pontoon: https://pontoon.mozilla.org/fr/thunderbirdnet/LC_MESSAGES/messages.po/?search=users+like&string=205740

I don't have access to approve it, however. Translation happens on there, so filing issues here isn't going to help much.

**Comment by HumanG33k** [comment]
10k tools/parts on 20k places where can i find a map ? I just follow the link on the website. Maybe a link translate can prevent other people error ? 

Thx by the way ;)
