### ISSUE TITLE
Supporters pictured on the about page.

### ISSUE THREAD

**Issue by MadMattAu** [thundernest/thunderbird-website#157]
The about page https://www.thunderbird.net/en-US/about/ shows a image of the Thunderbird Developers Toronto Summit 2014.  Not that I have anything against those folks,  but it is not in any way reflective of the current supporters, developers or the current team.  A stock photo from getty would be almost as appropriate.  I suggest it is simply removed.

**Comment by wsmwk** [comment]
I disagree as follows ... It's unfortunate that we don't have a current group picture (which would actually be impossible to accomplish without a summit), but we do not. As such, it's the best representation we have, and better than none. Add to that, the picture even when it was taken probably only had half the active people.  Further, 9or10 of 21 people in the picture are active. Finally, no average user seeing this picture is going to know the difference.

**Comment by Sancus** [comment]
To what end? While some of those people no longer work on Thunderbird, some still do, and in any case, many made major contributions for years. It's not like the photo is 20 years old, it's 5. People come and go. Not everything has to be constantly updated all the time to be relevant, nor is that practical.

There is already Issue #98 to add Council Member photos to this page and next time we have a Thunderbird gathering of some sort, which may happen in 2020, we will have an updated photo to add.

Until then, the existing photo is fine.
