### ISSUE TITLE
Subscribe form on screens smaller than 400px is not responsive

### ISSUE THREAD

**Issue by taylankasap** [thundernest/thunderbird-website#159]
Subscribe form in homepage is not responsive below 400px screens.

![image](https://user-images.githubusercontent.com/4192479/71589603-7dfa3780-2b36-11ea-9157-4bf82097377d.png)

The fix isn't complicated but there are obviously more than a single way to fix. So I wanted to consult before a PR because I don't know your conventions.

Pick one:
- Add .w-full.md:w-3/4 to the form and .flex-grow to the input. Remove .self-start from the form and .w-64 from the input. (This causes 100% width on screens below 768px though.)
- Apply max-width: 100% to the form by creating a .max-w-full rule.
- Apply max-width: 100% to the form by giving it a class.
- Wontfix since this is not that important.
- Something else. (got to have 100% coverage /s).

P.S: I don't even have a 320px device, I was just testing on devtools.

**Comment by Alecaddd** [comment]
IMHO the easiest solution would be to add `flex-col sm:flex-row` to the form and `w-full sm:w-auto` to the button.
Reactivating the `sm` media query just for this case seems a bit too much, and these days screens below 400px are pretty unusual.

For me it's a wontfix, but let's wait for @Sancus feedback on this.

**Comment by Sancus** [comment]
I'm going with wontfix as well, I looked at our stats, and less than 0.1%(1 in 1200 or so) have a 320 or lower screen width, and about 0.2% have anything less than 380. The button doesn't get really bad until 320 or below. And the rest of the site looks OK. We're not a mobile app, and I would be utterly shocked if anybody looking at the site on a device like this even scrolled down far enough to see the newsletter signup.
