### ISSUE TITLE
https://www.thunderbird.net/en-US/channel/ not redirected to https://www.thunderbird.net/en-US/#channel

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#160]
easy to do I hope.   ( https://www.thunderbird.net/channel/ - without the en-US - does redirect )

I can't say I know if there had been localized version of https://www.thunderbird.net/channel/

**Comment by Sancus** [comment]
Yeah. I like to discourage people from linking externally to specific languages, unless the page isn't localized. That page was always localized. However, I realize it's annoying for people who have the page in their browser histories etc.

So it's fixed now.
