### ISSUE TITLE
Link Missing for System requirements on docs for "Installing Thunderbird on Linux"

### ISSUE THREAD

**Issue by linamnt** [thundernest/thunderbird-website#161]
The links on this page: [https://support.mozilla.org/en-US/kb/installing-thunderbird-linux](https://support.mozilla.org/en-US/kb/installing-thunderbird-linux) that direct to the system-requirements is incorrect.

There are two instances of the link with the text "required libraries".

It should link to this: https://www.mozilla.org/thunderbird/latest/system-requirements/
but instead is this dead link: https://www.thunderbird.net/en-US/thunderbird/system-requirements/

Related: https://github.com/thundernest/thunderbird-website/issues/137
Thanks!

**Comment by Sancus** [comment]
The actual link on the page is to https://www.thunderbird.net/thunderbird/system-requirements/ which was supposed to be working but wasn't, I've fixed it now(note that you will need to clear cache or use a different browser to check, Firefox is very stubborn about caching redirects).

I also submitted an edit to the page, the current direct link to latest system requirements is https:/www.thunderbird.net/system-requirements/
