### ISSUE TITLE
Hide https://www.thunderbird.net/ja-JP-mac/

### ISSUE THREAD

**Issue by makotokato** [thundernest/thunderbird-website#162]
Actually, there is ja page as https://www.thunderbird.net/ja/, but https://www.thunderbird.net/ja-JP-mac/ is still alive too.

It means that `Page language:` in footer has 2 Japanese entries.

![lang](https://user-images.githubusercontent.com/965338/72867685-1beeb580-3d23-11ea-95c4-f82e024be373.png)

**Comment by Sancus** [comment]
We still release this locale as does Firefox so I'm not sure what the justification is for getting rid of it?

**Comment by Sancus** [comment]
I asked pmac on mozilla.org and he thinks this locale is only needed for client-side stuff, not for the website, so maybe a redirect -> ja should be happening here instead of a separate locale.

**Comment by Sancus** [comment]
This locale is now removed.
