### ISSUE TITLE
Thunderbird 68.4.2 release notes are missing

### ISSUE THREAD

**Issue by Mozinet-fr** [thundernest/thunderbird-website#163]
Clicking on the Release notes in Thunderbird 68.4.2 leads to a 404 error page.

**Comment by JDLH** [comment]
I encountered this also. As an end user of Thunderbird, I always click the "learn more…" link for an update before downloading the update. Is there a missing step in the release process, if an update can be announced via Thunderbird's update mechanism without the corresponding release notes being published?

**Comment by Sancus** [comment]
https://www.thunderbird.net/en-US/thunderbird/68.4.2/releasenotes/

**Comment by vcunat** [comment]
It's a bit confusing there that it says "various security fixes" but the linked page shows no security problems fixed in that release.

**Comment by wsmwk** [comment]
we'll fix it.
