### ISSUE TITLE
Add link to Pontoon in footer

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#168]
It would be helpful if there was a link to Pontoon in the footer, right now there is only a "Contribute to this site" link to this repository. People sometimes file translation issues on here and then I just end up redirecting them to Pontoon.

**Comment by RCMainak** [comment]
I would like to work on this issue.

Before I submit the patch I want to mention that the [get involved](https://www.thunderbird.net/en-US/get-involved/) page has all the links listed very nicely. I think removing the "Contribute to this site" link maybe a better solution.

Let me know what you think, after that I'll submit the PR.

**Comment by Alecaddd** [comment]
We shouldn't remove the "Contribute to this site" link as that's a direct access to this very own repo, and the CTA is clear and on point. The Get Involved page has a broader objective and it mostly focuses on Thunderbird.

I'd update the footer with "Contribute to this site • Translate this site", or something along those lines.
