### ISSUE TITLE
should be possible to link to sub-sections easily

### ISSUE THREAD

**Issue by mkmelin** [thundernest/thunderbird-website#169]
Many of the pages basically lack the ability to link to subsections. This would be useful for at least linking to the beta program, or to positions on the careers page. 

A common way for this is to have the an anchoring icon appear near the relevant header on hovering. Then with the id linked, the section may want to be highlighted with css :target

**Comment by Alecaddd** [comment]
Sure, I can do that.
I'll implement this for each H tag with an ID so they can be generated automatically.

**Comment by Sancus** [comment]
I already added this for beta, the beta link is https://www.thunderbird.net/#channel
