### ISSUE TITLE
Docker container for the website

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#17]
The website would be easier to locally develop on if there was a docker container for it.

**Comment by ryanleesipes** [comment]
I'm having issues getting the site to build with CSS and images intact - so I agree.

**Comment by ryanleesipes** [comment]
Using the command it loads the server, but the assets still aren't showing up @Sancus

**Comment by ryanleesipes** [comment]
Actually did get this working, detailed what I was overlooking in #21

**Comment by petedreizehn** [comment]
How should this look like? Do you imagine that the whole stuff is build in the Dockerfile or should the Dockerfile only serve the content which was build locally?

**Comment by ryanleesipes** [comment]
@petedreizehn I imagine someone grabbing the Dockerfile and being able to use it to develop the website. So everything needed to build should be included in there.

Does that answer your question?

**Comment by Sancus** [comment]
I'm closing this because I don't really want a docker container for just the website alone, if we do this I want one for all our static sites in one container, and tbh I think the website is plenty easy to install and work with now since I improved the build scripts.
