### ISSUE TITLE
Redirect from https://start.thunderbird.net/ja-JP-mac to https://start.thunderbird.net/ja/

### ISSUE THREAD

**Issue by makotokato** [thundernest/thunderbird-website#171]
Thunderbird home page seems to be `https://start.thunderbird.net/<locale string>`, so Thunderbird for macOS JA is ja-JP-mac, so https://start.thunderbird.net/ja-JP-mac/release seems to be not found page. (I guess that this may be regression by https://github.com/thundernest/thunderbird-website/issues/162).

So could you always redirect from `https://start.thunderbird.net/ja-JP-mac` to `https://start.thunderbird.net/ja/` ?

**Comment by Sancus** [comment]
Yes, thanks for the report and sorry about that.

This should be fixed now.

https://start.thunderbird.net/ja-JP-mac/release
