### ISSUE TITLE
Location of JS code

### ISSUE THREAD

**Issue by rejas** [thundernest/thunderbird-website#18]
Maybe a stupid question, but I can only find the minified/uglified javascript sources. Arent there any sources file for them here? Cheers, V

**Comment by Sancus** [comment]
JS is in the files referenced here: https://github.com/mozilla/bedrock/blob/master/bedrock/settings/static_media.py#L1023 for common-bundle.js and similarly for site-bundle.js

Yes, they should be in the repo and minified locally but they need to be heavily pruned anyway. It's on the list for eventually.

**Comment by rejas** [comment]
ok, thx for the info
