### ISSUE TITLE
https://www.thunderbird.net/en-US/get-involved/ links to dead location https://developer.thunderbird.net/the-basics/building-thunderbird

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#182]
The new location is https://developer.thunderbird.net/thunderbird-development/building-thunderbird

**Comment by Sancus** [comment]
Fixed in https://github.com/thundernest/thunderbird-website/commit/cd7723f164896eb5b50faf9176807a4ee7676854 and live now.
