### ISSUE TITLE
How to localize release notes?

### ISSUE THREAD

**Issue by pols12** [thundernest/thunderbird-website#187]
Just reading recent issues, e.g. #168, #148, I have understood that Pontoon is the place to contribute to localization.

However, release notes don’t seem to be on Pontoon. E.g. I would like to see [v68.3.0 release notes](https://www.thunderbird.net/en-US/thunderbird/68.3.0/releasenotes/) in French, but using the language select in footer leads me to HTTP404 (okay, that’s in French… -_-).

Is there another place than Pontoon to translate release notes?

**Comment by Sancus** [comment]
Release notes can't be localized currently. It's just not practical with the architecture. They get very little traffic, we push out a lot of them especially for betas, and Thunderbird is a low priority in Pontoon. It takes most languages weeks to complete localization of relatively small amounts of text, so it simply doesn't make much sense to push so much additional work to localizers when only a few people will benefit.

For major versions(once per year with new ESR), we do a separate "[What's New" page](https://www.thunderbird.net/de/thunderbird/68.0/whatsnew/) which is localizable along with the rest of the website, and is displayed by default to all users when they update.
