### ISSUE TITLE
[Feature Request] Add a "Get Involved" section

### ISSUE THREAD

**Issue by jerrac** [thundernest/thunderbird-website#19]
Could you add a Get Involved section in the main navigation?

It would be a page, or pages, that contain (or link to) the following information:

* Where to get the Thunderbird code
* How to start developing for Thunderbird
* Where to get help with development problems
* Where to initiate discussions about new features.
* A summary of all the ways you can communicate with/about Thunderbird
  * Forums https://discourse.mozilla.org/c/thunderbird
  * Mailing lists
  * IRC/Other Chat channels
  * This github repo issue queue
  * Etc...

I, personally, like how [LibreOffice](https://www.libreoffice.org/community/get-involved/) did it.

**Comment by ryanleesipes** [comment]
I think having this up at the top would be a good deal. I was actually brainstorming this the past couple of weeks, but @jerrac's concept is pretty solid.

**Comment by Sancus** [comment]
I think this is a fine idea, but it shouldn't be on the website. That just makes it unnecessarily difficult to maintain. We have various documents of a similar type on the Mozilla wiki like: https://wiki.mozilla.org/Thunderbird:Home

I'm not sure if there is an existing 'get involved' document somewhere on there or on MDN, but if there's not, I suggest building one as a wiki page and then we can link to it from the website. Then it's easy to update and also in the same place the rest of our developer documentation is.

**Comment by mkmelin** [comment]
FWIW, the current Get involved doc is https://wiki.mozilla.org/Thunderbird#Contributing

**Comment by wsmwk** [comment]
Indeed. We point to the wiki from the in-product Thunderbird start page 
AND release notes https://www.mozilla.org/en-US/thunderbird/releasenotes/

Wiki is very handy for making improvements and corrections - 
indispensable IMO.  However, the downside it is not localized.

**Comment by jerrac** [comment]
Hmm... I had been thinking it would be a good idea to adapt that wiki page content into what would be on the Get Involved page. I was linked to it on the forum sometime after I posted this issue.

But if pushing changes to the content is more important than having the content live on the site, maybe just link directly to the Wiki from the "Get Involved" menu item would be enough?

After browsing the wiki some, I do think that most/all of my initial questions would have been answered if I had been directed to it from the start.

**Comment by Sancus** [comment]
Well, if we want to do a fully localized Get Involved page, we can do so. The time to make changes to localized pages on a static website is much longer than to a wiki, and requires actual HTML/CSS be written as well, so I prefer to push documentation needs to the wiki when possible. 

Almost all our documentation for contributors/developers is in English so I assume that anyone who does want to contribute is going to need to be able to read English to some extent anyway. Which is maybe not ideal, but support for non-English-speaking contributors is challenging.

If this is something we want anyway that's totally fine, it's just more complex and time consuming than a wiki page so the question is whether it's worth it or not.

**Comment by jerrac** [comment]
Would it be possible to come up with a generic enough "Get Involved" page that it wouldn't need to be updated very often? 

I did check and see that the revision history of "Thunderbird:Home" is fairly short, for a 10+ year old page.

I'm not very good at front end design, or technical writing, but would it help us figure out the benefits if I prototyped out something? I think I could take the Features page and use it as a template for a Getting Started page.

Before I try that, though, is there a specific site generator being used, or is this custom python?

It looks like Jinja2 templates?

**Comment by mkmelin** [comment]
I think it would be useful to have a more appealing Get involved page than what a wiki can provide. Yes, like https://www.libreoffice.org/community/get-involved/ mentioned earlier above.

Not sure it really needs to be localizable - I'd lean towards not localizing. The truth is if you don't know enough English to read a page like that, you won't be able to communicate and participate in the community. Or maybe there are efforts possible, but those would be completely on your own.

**Comment by ryanleesipes** [comment]
A generic page like libreoffice's that points at the different places that you can get involved is good. @jerrac prototyping something could be useful. I think calling it "Get Involved" is a good idea. You should be able to follow the instructions on the README to build the site, and then run:

`python -m SimpleHTTPServer 8000` in the directory with the index file.

Let me know if that works for you.

**Comment by jerrac** [comment]
I've stubbed out a page with a few sections base on what LibreOffice has. I think I've figured out some of the syntax for this static site builder, but I want to double check before I get too far.

The site pages are basically Jinja templates. Like what I use in Ansible. Right?

```
{{ _('Test') }}
```
is how translated text gets replaced. Correct?

I see:

```
{% if LANG.startswith('en-') %}
{% endif %}
```
All over the features template. That is how you exclude a section from any non-English sites. Correct?

From the conversation in this issue, I'm guessing we are not planning on translating a Get Involved page. So, should I bother with the `_()` translation for anything?

If we're excluding the entire page from all non-English sites, is there a way to do that per page? Or should I be wrapping everything in `{% if LANG.startswith('en-') %}{% endif %}`?

If I need to make style changes, should I create a `/assets/less/thunderbird/get-involved.less` file, and then include it in the `build-site.py` files `css_bundles` section?

I've forked this repo, and am making changes on a new branch. What is the best way to share those changes to get feedback before I make a pull request? Or should I just make a pull request in order to get feedback?

**Comment by Sancus** [comment]
1. Please include the gettext calls[_('whatever')] for all text whether or not it's meant to be english-only. We have a number of english-only pages already but they include it, it's not a good mechanism to avoid localization.
2. Since this entire page is not going to be translated, don't worry about the if statements or about excluding it from translation. Just do it as a regular page. If/When it gets merged I'll worry about it, since our translation system is not really complete yet.
3. Yes, you should make a new LESS file if style additions are required, and the css_bundles is the place to include it.
4. Making a pull request is the best way to get feedback.

**Comment by jerrac** [comment]
@Sancus Thanks!

**Comment by ryanleesipes** [comment]
Thanks @jerrac - if you want to chat me up, feel free. You can get me @ryanleesipes on Telegram, or ryanleesipes-m on IRC (Moznet), or ryanleesipes on riot.im

More than happy to offer feedback and we can discuss ideas!

**Comment by ryanleesipes** [comment]
Linked to #28 - see PR for more info.

**Comment by Sancus** [comment]
https://www-stage.thunderbird.net/en-US/get-involved/

This is excluded from string extraction and the menu only shows on en-* language pages.

**Comment by ryanleesipes** [comment]
I think this looks great! How long til' it shows up on thunderbird.net proper?

**Comment by Sancus** [comment]
It's live as of yesterday.

**Comment by ryanleesipes** [comment]
Great!

**Comment by jerrac** [comment]
It was fun working on this with everyone. I learned a lot from it. Thanks!
