### ISSUE TITLE
"More info" link of the available update pop-up is a dead link

### ISSUE THREAD

**Issue by Freeedim** [thundernest/thunderbird-website#192]
Hi there!

When I clicked on the "More info" (sorry, I don't know the exact English label) link at the bottom of the small pop-up notifying me that new version 68.10 is ready to be downloaded, I ended up on a HTTP 404 error page. The link points to:
https://www.thunderbird.net/en-US/thunderbird/68.10.0/releasenotes/?uri=/thunderbird/releasenotes/&locale=fr&version=68.10.0&channel=release

I tried removing the locale parameter:
https://www.thunderbird.net/en-US/thunderbird/68.10.0/releasenotes/?uri=/thunderbird/releasenotes/&version=68.10.0&channel=release
... But same result.

I also tried:
https://www.thunderbird.net/en-US/thunderbird/68.10.0/releasenotes
But it is dead too.

It actually makes sense since on this page, no 68.10 version appears (as of today, 1st July 2020, at 6:30 UTC:
https://www.thunderbird.net/en-US/thunderbird/releases/

Cheers!

**Comment by int-red** [comment]
the English link label is "Learn more..."

Had the same issue with the English Thunderbird.

**Comment by c-e-github** [comment]
Same issue with German version: Click on "Neue Funktionen und Änderungen" leads to a "There’s nothing here!" page.
This should be remedied ASAP.

**Comment by wsmwk** [comment]
There was a problem last night - resolved approximately two hours ago.

**Comment by Sancus** [comment]
This seems like it was resolved, and was just the release notes missing for a short time.
