### ISSUE TITLE
Startup with last shown message/account not working anymore...

### ISSUE THREAD

**Issue by TeddAndersen** [thundernest/thunderbird-website#194]
Thunderbird 78 / 64bit / windows 10
Is it a bug or feature that thunderbird always start with the newest message of the first account.... and not the message/account that was active when closing down ? Or is there a setting somwhere that changes this back to the old settings?

**Comment by mkmelin** [comment]
Feature, but has nothing to do with the Thunderbird website. (Thunderbird bugs are in bugzilla)
