### ISSUE TITLE
The redirect after a new version install goes to an empty page

### ISSUE THREAD

**Issue by s0ftwhere** [thundernest/thunderbird-website#196]
After installing the new version of Thunderbird (78), the browser opens the following link (from a windows PC):
https://www.thunderbird.net/en-US/thunderbird/78.0/releasenotes/whatsnew/?locale=en-US&version=78.0&channel=release&os=WINNT&buildid=[redacted]

However, this link is empty. (The page you are looking for doesn’t exist.)
(I have just redacted my build id but the rest of the url is the same.)

The actual link should probably be: https://www.thunderbird.net/en-US/thunderbird/78.0/releasenotes/#whatsnew

**Comment by Sancus** [comment]
This is fixed, though cached redirects may cause some languages to still redirect wrongly until tomorrow.
https://live.thunderbird.net/thunderbird/whatsnew/?locale=en-US&version=78.0&channel=release&os=WINNT&buildid=20200713151512 works for me now.
