### ISSUE TITLE
Calendar page not fully localized

### ISSUE THREAD

**Issue by DaddyAG** [thundernest/thunderbird-website#197]
https://www.thunderbird.net/hr/calendar/

If you visit link above you will see which parts of page aren't fully localized (all english text).

- Organize your life — it’s about time!
- Organize your schedule and life’s important events in a calendar that’s fully integrated with your Thunderbird or Seamonkey email. Manage multiple calendars, create your daily to do list, invite friends to events, and subscribe to public calendars.
- Other Systems & Versions
- COMPATIBILITY INFORMATION
- Thunderbird, Seamonkey, what version?
- Need help with Lightning?
- HOLIDAY CALENDARS
- Need a break? Now you know when!
- DEVELOPER TOOLS
- Dive into development.
- BUGZILLA
- Found a bug? Let us know!
- BUGS AHOY!
- Want to make a difference? Fix a bug that fits your interests.

Some of those strings aren't available for translation and some are already translated, but not showing on webpage for some reason.

For example:
https://pontoon.mozilla.org/hr/thunderbirdnet/LC_MESSAGES/messages.po/?string=205762
https://pontoon.mozilla.org/hr/thunderbirdnet/LC_MESSAGES/messages.po/?string=205738

As you can see here, https://pontoon.mozilla.org/hr/thunderbirdnet/ , webpage is fully translated on Pootle.

**Comment by Sancus** [comment]
This is fixed now; this page wasn't translated before the new website and it got lost in the shuffle. Thanks for the report.
