### ISSUE TITLE
`pip install requirements.txt`, `python build-start.py`, `python build-site.py` all fail

### ISSUE THREAD

**Issue by jerrac** [thundernest/thunderbird-website#20]
I cloned the master branch so I could see what it would look like if I tried to contribute anything to it. Unfortunately, I can't get it to build.

```bash
$ pip install requirements.txt 
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
```
I ran into that, so I manually ran pip install commands for each item in requirements.txt.

After that:

```bash
$ python build-start.py 
Traceback (most recent call last):
  File "build-start.py", line 1, in <module>
    from staticjinja import make_site
ImportError: No module named staticjinja
```
and
```bash
$ python build-site.py 
Traceback (most recent call last):
  File "build-site.py", line 2, in <module>
    import helper
  File "/home/user/dev/sites/thunderbird-website/helper.py", line 3, in <module>
    import markdown
ImportError: No module named markdown
```
pip reported that both staticjinja and markdown were already installed when I tried manually installing them.

This is on Ubuntu 16.04.

Any suggestions?

**Comment by z0rb** [comment]
The README.md needs to be fixed, it should be:
`pip install -r requirements.txt`

**Comment by jerrac** [comment]
`pip install -r requirements.txt` just says "Requirement already satisfied" for all the modules when I run it. The build scripts still output the same error.

**Comment by Sancus** [comment]
Thanks for the note about the missing '-r' for pip install, was a typo, and I've fixed it.

I can't tell you why you are getting these error messages - I just tested on a brand new Ubuntu 16.04 VM, and after installing git, python-pip, and then following the directions(swapping apt-get for yum, of course, with the npm installation) everything works fine.

You should be able to simply type 'python' to bring up the console and then 'import markdown'. If that doesn't work, something must be wrong with your python path or pip installation that python is unable to find the installed packages. There is nothing wrong with the website or the build scripts that I can find. I'll leave this open for a little longer and then close it.

**Comment by jerrac** [comment]
Ok, so it is just me. Good to know. Annoying, though....

Any suggestions on how to troubleshoot my python issues? I know the basics of the language, but I have yet to learn its ecosystem.

Using your import tip, this is what I get:
```
$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named markdown
>>> 
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
>>> 
```
If I try using python3 on the buiild-site.py script, here's what I get:
```
$ python3 build-site.py 
  File "build-site.py", line 112
    print "Rendering {0}/index.html...".format(target)
                                      ^
SyntaxError: invalid syntax

```

**Comment by jerrac** [comment]
I had tested on a new vm before and ended up in the same broken situation. But I tried that again, and everything started working... 

Until I hit this:

```bash
$ python build-site.py
< Rendering blah lines go here>

Traceback (most recent call last):
  File "build-site.py", line 134, in <module>
    build_assets()
  File "build-site.py", line 49, in build_assets
    env[k].urls()
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/bundle.py", line 806, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/bundle.py", line 765, in _urls
    *args, **kwargs)
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/bundle.py", line 619, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/bundle.py", line 543, in _merge_and_apply
    kwargs=item_data)
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/merge.py", line 276, in apply
    return self._wrap_cache(key, func)
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/merge.py", line 218, in _wrap_cache
    content = func().getvalue()
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/merge.py", line 251, in func
    getattr(filter, type)(data, out, **kwargs_final)
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/filter/less.py", line 139, in input
    self._apply_less(_in, out, source_path)
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/filter/less.py", line 131, in _apply_less
    self.subprocess(args, out, in_)
  File "/home/<localusername>/.local/lib/python2.7/site-packages/webassets/filter/__init__.py", line 527, in subprocess
    proc.returncode, stdout, stderr))
webassets.exceptions.FilterError: less: subprocess returned a non-success result code: 1, stdout=, stderr=SyntaxError: Inline JavaScript is not enabled. Is it set in your options? in - on line 137, column 17:
136             &[class*="android"] a {
137                 .at2x('/media/img/firefox/all/download-icons-android.png', 40px, 120px);
138                 background-position: 0 0;
```
Does the less node module have options users can set somewhere?

**Comment by Sancus** [comment]
I guess that the install on Ubuntu 16 defaults to less > 3.0 now.
Try 
`sudo npm remove -g less`
`sudo npm install -g less@2.7.2`

**Comment by jerrac** [comment]
FYI, the last error was on an Ubuntu 17.10 vm.

But, with the correct version of less, I was able to get a successful build. Yay!

Thanks for the help everyone!

**Comment by jerrac** [comment]
I finally ran down the issue on my main development machine. I had installed `python3-pip`. So `pip` was running under python 3, and the build scripts need version 2. Once I used `pip2 install -r requirements.txt` the build scripts started working.

A bit off topic, but is there a way to limit what the build-site.py actually builds? If I make a small css change, I don't want to build the entire site all over again just to make sure it applies when built. I also found I have to restart the SimpleHTTPServer since the thunderbird.net directory is deleted before being rebuilt.

A more general question would be what kind of workflow should I use?

I'm still feeling my way around where to ask questions like that, should I create a new topic? Post on the discourse forum? I'd have asked in IRC, but I don't have time to get on right now. :)

Thanks!

**Comment by Sancus** [comment]
There's no way to limit what build-site.py builds. You can comment out bits of it if you know what parts are generating what you need, that's about it. Doing limited builds properly is very non-trivial and it wasn't needed for development so I didn't consider adding it. It's a future enhancement that would be nice, for sure, but with builds under 15 seconds on a low-end linode it's not a priority for me.

If you are just making frequent small CSS tweaks trying to get something to look right, you should use your browser's inspector tools for that and only apply the changes to the site after you have figured out exactly what you want to change.

Issues are not really the ideal place for discussion/questions so if you want to make a thread on the discourse that's fine, I'll follow it and respond as I have time.
