### ISSUE TITLE
TB 78.3.0 released but no releasenotes

### ISSUE THREAD

**Issue by italiangm** [thundernest/thunderbird-website#215]
The "Release notes" link provided in "About Thunderbird" popup sends us to https://www.thunderbird.net/en-US/thunderbird/78.3.0/releasenotes but there is no content.

**Comment by italiangm** [comment]
UPDATE: It appears 78.3.0 has been withdrawn since the update button no longer appears in "About Thunderbird".

**Comment by wsmwk** [comment]
Thanks for reporting this. It is still unknown why it is not showing.  But yes, 78.3.0 has been withdrawn.

**Comment by philgp** [comment]
Should those of us whose Thunderbird updated itself to 78.3.0 download and (re)install 78.2.2? @wsmwk

**Comment by mkmelin** [comment]
It was withdrawn due to a crasher. If you don't crash, no need for action.

**Comment by wsmwk** [comment]
> It was withdrawn due to a crasher. If you don't crash, no need for action.

Correct.  Also, what I am seeing in the crash system suggests people crash on average only once.  So far that has also been my personal experience - I have crashed only once in the 10 hours that 78.3.0 has been installed.

**Comment by Sancus** [comment]
Release notes are up, also.
