### ISSUE TITLE
New UK Holidays Calendars

### ISSUE THREAD

**Issue by KR304** [thundernest/thunderbird-website#219]
Hi all, sorry if I have not obeyed the correct protocol, this is my first time contributing to something like this and I only just made a GitHub account!

I have created four holiday calendars for UK residents to last between 2021 and 2030. These holidays are public ('bank') holidays only. The UK is split into four nations - England, Wales, Scotland and Northern Ireland. England and Wales have the same bank holidays. Scotland and Northern Ireland have most of the same holidays, but also some of their own.

So I've created one calendar for English & Welsh residents, one for Scottish residents, and one for Northern Irish residents. I have created a fourth UK-wide calendar, containing all holidays across all four nations.

[UK Bank Holidays 2021-30.zip](https://github.com/thundernest/thunderbird-website/files/5488909/UK.Bank.Holidays.2021-30.zip)

**Comment by justdave** [comment]
The referenced pull request only implements the UK-wide calendar because that's what was already in there to update... will defer to @Sancus about whether/how to include the individual nation calendars.

**Comment by justdave** [comment]
The individual calendars have also been added to the PR now.
