### ISSUE TITLE
Update Colombia holidays calendar until 2050

### ISSUE THREAD

**Issue by mauricio8502** [thundernest/thunderbird-website#225]
Hi friends. I made the first version of the Colombia holidays calendar from 2000 to 2020 (which is currently published at https://www.thunderbird.net/en-US/calendar/holidays). Now I send you the update from 2000 to 2050. Best regards. 

[Colombian holidays 2000-2050.zip](https://github.com/thundernest/thunderbird-website/files/5712488/Colombian.holidays.2000-2050.zip)

**Comment by justdave** [comment]
Committed, thanks!
