### ISSUE TITLE
Australia Holidays ics 2021-2022

### ISSUE THREAD

**Issue by RGreyman** [thundernest/thunderbird-website#226]
I have created a calendar containing the Australian Public Holidays as listed at data.gov.au on 21/12/2020.
[Australia Holidays.zip](https://github.com/thundernest/thunderbird-website/files/5720981/Australia.Holidays.zip)

**Comment by justdave** [comment]
huh. There's an existing file for Australia in here that looks like it hasn't been updated since 2013.  Probably why it's gone off the index.

Added back to the index pointing at this file.  Thanks!
