### ISSUE TITLE
translation information is incorrect at get-involved

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#228]
per https://bugzilla.mozilla.org/show_bug.cgi?id=1643591  https://www.thunderbird.net/en-US/get-involved/#translation should point to something like https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Thunderbird/Thunderbird_Localization - we're not yet on pontoon

**Comment by justdave** [comment]
OK, Just to clarify from that discussion since what's on the bug is ambiguous...  is just German and Spanish missing from Pontoon, or is Thunderbird in general not using it at all?

**Comment by justdave** [comment]
I guess it doesn't really matter because the Thundbird Localization page on devmo should be updated to reflect what the current situation is and so pointing there is good.  Well, I suppose that page really ought to be moved to DTN but that's likely a different bug.

**Comment by justdave** [comment]
Since the website is localized (heh, we're on topic) what's my procedure for updating this?  Do I just update the English and the other locales just see the new English sentence in that spot until localizers notice there's a new string that needs translating?

**Comment by justdave** [comment]
poked around, figured out how the localization works, discovered the config is set up to exclude this page from getting localized anyway, so I guess I don't have to worry about it.
