### ISSUE TITLE
HungarianHolidays has expired

### ISSUE THREAD

**Issue by Mishy1973** [thundernest/thunderbird-website#235]
Hungarian Holidays and Namedays are attached in two separeted files.
Namedays are repeats for ever, not expiring.
Holidays are valid until 2050.
The present calendar on thunderbird page:
https://www.thunderbird.net/en-US/calendar/holidays/ expired et the end of 2020.

[HungarinNamedays_and_Holidays_until-2050.zip](https://github.com/thundernest/thunderbird-website/files/5858946/HungarinNamedays_and_Holidays_until-2050.zip)

Regards,
Mishy

**Comment by Mishy1973** [comment]
The ZIP has spelling error (Hungarin>Hungarian) but the content OK! :)

**Comment by Mishy1973** [comment]
Good Friday correction added, Both Namedays and Holidays are separately uploaded now.
[HungarianHolidays_until-2050.zip](https://github.com/thundernest/thunderbird-website/files/5862984/HungarianHolidays_until-2050.zip)
[HungarianNamedays.zip](https://github.com/thundernest/thunderbird-website/files/5862985/HungarianNamedays.zip)

**Comment by Sancus** [comment]
Something is busted with HungarianHolidays.ics, it does not pass import test.

**Comment by Mishy1973** [comment]
Hi!
Have you tested my most recent upload?
I works with no warning on Thunderbirtd 78.6.0 64bit Linux.
59edb8461921c3a237c57a9c52335e0c  HungarianHolidays.ics

**Comment by Mishy1973** [comment]
Some more corrections on Pentecost (Monday ditiction removed)
md5sum:
9e1b6aa8e92c1174e430cae2ef28d073  HungarianHolidays.ics
It also passes the import test on Thunderbirtd 78.6.0 64bit Linux.
[HungarianHolidays.ics.zip](https://github.com/thundernest/thunderbird-website/files/5865373/HungarianHolidays.ics.zip)

**Comment by Mishy1973** [comment]
Shall I help anything to get it posted?
The latest HungarianHolidays.ics.zip (previous post) and the HungarianNamedays.zip should be Okay.

Please contact me if I can help anything.

**Comment by Sancus** [comment]
We have [a script](https://github.com/thundernest/thunderbird-website/blob/master/l10n_tools/check_calendars.py) that checks these calendars before import, and it finds errors in this one. I don't really have time to dig into what the exact problem is right now. This is a recurring issue with calendars and why we really prefer proper pull requests.

Thunderbird is prone to accepting calendars even with errors in them, it just refuses to parse the bits that have problems. In this case, it shows a bunch of errors on import:

![image](https://user-images.githubusercontent.com/479671/109439624-fc28c700-79e3-11eb-849e-8a30e0c71f98.png)
