### ISSUE TITLE
Outdated Calendar links pointing to developer.mozilla.org

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#236]
https://www.thunderbird.net/en-US/calendar/ has two outdated links
- Compatibility information pointing to https://developer.mozilla.org/en/Calendar/Calendar_Versions
- Developer Tools pointing to https://developer.mozilla.org/en-US/Calendar/

**Comment by Sancus** [comment]
I deleted these two links, the first one is no longer relevant as we don't build Thunderbird as a separate add-on anymore, and the second hasn't had useful information for years.

Honestly, not too sure we should keep the calendar project page at all...
