### ISSUE TITLE
Download issues and Debian

### ISSUE THREAD

**Issue by pedromorgan** [thundernest/thunderbird-website#241]
So am using Thunderbird (mainly as a testing and babysitting mailbox system)

- so thanks to [hacker news](https://news.ycombinator.com/item?id=26543495)
- decided to try latest.. cos its not life changing as an auxiallty mailagent

## Downloads page missing kinda
so here
- https://www.thunderbird.net/en-GB/download/

- there's no direct link to the binaries, instead it pops up and detect my platform..
- maybe i want to download windows version to memory stick on a linix machine
- so options need to be there for platforms etc (example [python download](https://www.python.org/downloads/))

## Debian ppa

- are there ppa's yet of a stable deb to download ?

**Comment by Sancus** [comment]
Hi, glad to see people interested.

We have a page for that: https://www.thunderbird.net/en-US/thunderbird/all/

You can get to it by clicking "Systems & Languages" underneath the download button on the main page. Keep in mind that the average user(>90% Windows) does not want to be presented with a bunch of buttons and have to figure out which one is right on their own.

idk anything about the state of debian ppas or anything, maybe @jfx2006 does? In any case not a website bug.

**Comment by jfx2006** [comment]
Debian doesn't have PPAs that I'm aware of, that's more of an Ubuntu thing AFAIK. There might be something on Launchpad somewhere. I can't say for sure and I wouldn't recommend one anyway without taking a look at how it's built.
Currently, the only Linux builds that we have are the tar files.

**Comment by jfx2006** [comment]
@pedromorgan: I happened across this project on Sourceforge that seems to be what you're looking for.
https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/

I can't vouch for the packaging quality, but a quick glance suggests that the project has been around for some time in one form or another and it does have an up-to-date APT repository with Thunderbird-78.9.0. It looks like it's repackaging the official builds.
