### ISSUE TITLE
Updated holiday calendar file for Iceland

### ISSUE THREAD

**Issue by kristjanbjarni** [thundernest/thunderbird-website#242]
The current holiday calendar for Iceland has expired. I created a new file with dates from 2021 - 2060. Can you please update the link with this new version

[IcelandHolidays.zip](https://github.com/thundernest/thunderbird-website/files/6223543/IcelandHolidays.zip)

**Comment by Sancus** [comment]
Fixed by https://github.com/thundernest/thunderbird-website/commit/e00f1b4b7175ba4e9261f9acfe7827ada32c81ee
