### ISSUE TITLE
Update the wording from Nightly to Daily

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/thunderbird-website#247]
If I'm not wrong, `Nightly` is used for Firefox while `Daily` is used for Thunderbird.
I think we should update the wording around the website to reflect this aspect, especially in the pre-footer tabs to download the different versions.

We should also update the icons to use one with the "daily" text on it, like we currently use in the builds: https://searchfox.org/comm-central/rev/faba8b4037ce7434416ee2f5fb2d00497675795b/mail/branding/nightly/content/about-logo.svg

**Comment by Sancus** [comment]
Yeah it's always been like that. I could have sworn there was an intent to change to Nightly which is why we used those wordings on the new site design. But I can't really remember.

In any case, it seems like we're sticking with Daily so might as well.

**Comment by Alecaddd** [comment]
@mkmelin what do you think?
Do you agree with updating our wording to consistently refer to "Daily" instead of "Nightly"

**Comment by mkmelin** [comment]
Sounds good to me.

**Comment by Alecaddd** [comment]
[tb-logo-beta-daily.zip](https://github.com/thundernest/thunderbird-website/files/6417438/tb-logo-beta-daily.zip)
For the record, the updated BETA and DAILY logo.

**Comment by justdave** [comment]
The directory on the FTP server is https://ftp.mozilla.org/pub/thunderbird/nightly/
Can't easily change that one...

**Comment by justdave** [comment]
> For the record, the updated BETA and DAILY logo.

These look visibly different from the release logo (darker shade of blue). Do we have an outdated release icon on the website, too?

**Comment by justdave** [comment]
@Alecaddd 
> For the record, the updated BETA and DAILY logo.

These look visibly different from the release logo (darker shade of blue). Do we have an outdated release icon on the website, too?

**Comment by Sancus** [comment]
![image](https://user-images.githubusercontent.com/479671/124068784-feca1600-d9ef-11eb-95ba-3ad0a44c09d0.png)

Here's what the two icons look like. So yeah, the new ones are darker for some reason. I don't know if this is an SVG rendering issue, or the SVGs themselves are the problem. We should figure this out before we push the changes.

**Comment by Alecaddd** [comment]
@Sancus Updated the SVG logos to all be identical and use the same bird from the default.
[thunderbird-logos-SVG.zip](https://github.com/thundernest/thunderbird-website/files/6788777/thunderbird-logos-SVG.zip)
