### ISSUE TITLE
Clean upgrade from Window 7 to 10.  How do I get my Previous Thunderbird?

### ISSUE THREAD

**Issue by jacobstim1** [thundernest/thunderbird-website#249]
I had to upgrade from Window 7 to 10 due to Turbotax.  I never would have otherwise.
Anyway, my Thunderbird was the latest as of 2 months ago, and then I installed the windows 10 version what eve difference that makes.  But I can't seem to get my old mail - which is almost 20 years worth.  I lost all my contacts and everything.

Someone show me the magic on getting the old to the new?

Or make a button that does the find old stuff and transfer to new.

I did not have a backup.

I added a new Drive- SolidState and just went from there.

Tim

**Comment by Sancus** [comment]
Hi, this is a bug tracker for the website, not the support site. Support is here: https://support.mozilla.org/en-US/products/thunderbird

Thunderbird stores its email and other profile data in `C:\Users\<username>\AppData\Roaming\Thunderbird\Profiles\xxxxxxxx.default\`, so you'd have to find it on whatever drive it was previously installed on. Good luck.
