### ISSUE TITLE
Firefox <87 on MacOS 11.0 user agent breaks download buttons

### ISSUE THREAD

**Issue by bardonelgen** [thundernest/thunderbird-website#251]
The homepage says "Your system doesn't meet the requirements to run Thunderbird." 

The beta download page tells "Your system doesn't meet the         to run Thunderbird." No requirements even existing.

**Comment by Sancus** [comment]
As far as I can tell, there is no general issue with Mac OS 11, no.

What is your user agent? You can ```google "my user agent"``` and it should tell you at the top, a string like: ```Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15```

**Comment by bardonelgen** [comment]
I’m on Firefox:

Mozilla/5.0 (Macintosh; Intel Mac OS 11; rv:86.0) Gecko/20100101 
Firefox/86.0

**Comment by Sancus** [comment]
That is very strange. As far as I know, it should be ```11_0_0```, not just 11. And the current version is 11.3....

Well, in any case, I'll fix it tomorrow.

**Comment by Sancus** [comment]
Also, it seems like this was changed in Firefox 87 anyway: https://bugzilla.mozilla.org/show_bug.cgi?id=1679929

**Comment by bardonelgen** [comment]
Maybe it’s a temporary thing with the current Firefox release; my exact OS version is 11.3.1 (20E241)

Interesting enough, my Safari browser still gives a 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

**Comment by Sancus** [comment]
> Maybe it’s a temporary thing with the current Firefox release; my exact OS version is 11.3.1 (20E241)

The current version of Firefox is 88.0.1, not 86.0, so you're two versions behind. I am pretty sure this is a bug. The correct user agent for MacOS X 11 should say something like, "Intel Mac OS X 11_3_1", or the "Intel Mac OS X 10_15_7" you mentioned above which is something Apple did to maintain web compatibility.

I can find practically no references to "Intel Mac OS 11" on Google. I suggest you update your browser as I'm 99% sure your user agent is going to cause compatibility issues with other websites.

**Comment by Sancus** [comment]
The fix for this is live now.
