### ISSUE TITLE
Singapore Public holidays for 2021 and 2022

### ISSUE THREAD

**Issue by sulph68** [thundernest/thunderbird-website#252]
These are the ICS files for Singapore public holidays in 2021 and 2022
It would be good to have them accessible in TB
[public-holidays-sg-202x.zip](https://github.com/thundernest/thunderbird-website/files/6471543/public-holidays-sg-202x.zip)

**Comment by Sancus** [comment]
This should be one ics file for both years, we don't list multiple files like that. Also I'd suggest generating more than 2 years if you like! Up to you though.

**Comment by sulph68** [comment]
These are files provided by the singapore government manpower ministry... or if you guys can provide a way to link to their page for users to download. https://www.mom.gov.sg/employment-practices/public-holidayshttps://www.mom.gov.sg/employment-practices/public-holidays

**Comment by justdave** [comment]
Looks like the template does actually let us do two files for the same country.  #260 currently has that, and the built site doesn't look too bad...  it just lists Singapore twice with a different year after it on each one.

If that's okay, the proposed PR should take care of it.  If not, I can merge them, but given that it's an official government source I don't know if we should modify them any.
