### ISSUE TITLE
HTTPS certificate expired today 2021/08/09 for "addons.thunderbird.net"

### ISSUE THREAD

**Issue by Juraj-Masiar** [thundernest/thunderbird-website#265]
![Screenshot 2021-08-09 15 32 14](https://user-images.githubusercontent.com/6358971/128715578-22bd2434-e91c-4c8f-8e83-4cbe0762a4b1.png)

**Comment by adudek16** [comment]
The entire *.thunderbird.net cert has expired so this applies to all subdomains of thunderbird.net

**Comment by paulmenzel** [comment]
Seems to have been fixed in the meantime?

```
$ openssl s_client -connect addons.thunderbird.net:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = *.thunderbird.net
verify return:1
---
Certificate chain
 0 s:CN = *.thunderbird.net
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
[…]
SSL handshake has read 2580 bytes and written 394 bytes
Verification: OK
[…]
```

**Comment by Juraj-Masiar** [comment]
Look, they switched to "Let's encrypt" :)

![Screenshot 2021-08-09 16 21 17](https://user-images.githubusercontent.com/6358971/128722041-d637bb05-b540-452f-a417-bdefa9d0cb82.png)

**Comment by Sancus** [comment]
Thanks for the report. Just for posterity: What happened here was a Cloudflare issue that I'm still investigating. They resolved it on their own, however. I'm quite displeased that it happened at all, hopefully anything like this can be prevented in the future.
