### ISSUE TITLE
Calendar export/import

### ISSUE THREAD

**Issue by JohnStaf** [thundernest/thunderbird-website#268]
Using Thunderbird 91 in Win10_64 and latest Linux Mint_x64. Export calendar in Windows *ics file saved. Go to Linux and attempt to import the saved ics file. Nothing happens - file is not imported. The file is not large. No error message. Made a trial calendar in Google Calendar which imported to Linux Thunderbird OK. At a loss as to what might be going on.

**Comment by Sancus** [comment]
This is a place for bug reports about the website, not support or Thunderbird bug reports.
Support is here: https://support.mozilla.org/en-US/products/thunderbird
Bugs are reported here: https://bugzilla.mozilla.org/enter_bug.cgi
