### ISSUE TITLE
markupsafe not found

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/thunderbird-website#270]
I'm trying to install the requirements in Ubuntu 21.04 and I'm getting this error.
```
ERROR: Could not find a version that satisfies the requirement markupsafe==1.0
ERROR: No matching distribution found for markupsafe==1.0
```

I tried installing that dependency manually but when trying to build the website I get this error:
`ImportError: No module named jinja2`

**Comment by jfx2006** [comment]
I take it this is the command from README.md throwing the error?
```
pip install -r requirements.txt
```
This should work...
```
pip3 install -r requirements-dev.txt
```

If I'm not mistaken, the website is still running with Python 2.7, and that's probably where the discrepancy comes from. I noticed that with Python3/pip3 on Ubuntu 21.04 it pulled in markupsafe-2.0.1.

**Comment by Alecaddd** [comment]
I tried that and it doesn't work unfortunately.

**Comment by Alecaddd** [comment]
the `markupsafe` issue has been solved, but now I have another issue :D 
```
Traceback (most recent call last):
  File "/home/alecaddd/Mozilla/thunderbird-website/build-site.py", line 3, in <module>
    import feedparser
  File "/home/alecaddd/.local/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```

I'm on `python3.9.5` and based on the changelogs it seems that `decodestring` has been deprecated since v3.1

```
base64.encodestring() and base64.decodestring(), aliases deprecated since Python 3.1, have been removed: 
use base64.encodebytes() and base64.decodebytes() instead. (Contributed by Victor Stinner in bpo-39351.)
```
https://docs.python.org/3/whatsnew/3.9.html

**Comment by Alecaddd** [comment]
This is an issue with Feedparser, which needs to be updated to v6 or newer in order to be used with Python 3.
https://github.com/kurtmckee/feedparser/issues/201

**Comment by Sancus** [comment]
So when I did my install, I ended up with feedparser 6.0.8. The requirements file specifies feedparser>=5.2.1 so I have absolutely no idea why you would end up with any lesser version.

Regardless, it is fine to just force install feedparser 6.0.8 and you can update requirements-dev to require >=6.0.2 if you want.

**Comment by Alecaddd** [comment]
Strangely enough, my `python3 install` was stuck on version 5.2 and didn't care about v6 of Feedparser.
I had to manually remove it and install it by specifying the required version.
This works for me now, closing the issue.
