### ISSUE TITLE
Broken Localization links in Get Involved page

### ISSUE THREAD

**Issue by Parodper** [thundernest/thunderbird-website#274]
The link [Thunderbird Localization](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Thunderbird/Thunderbird_Localization) from [Get Involved, section *Translation*](https://www.thunderbird.net/en-US/get-involved/#translation) is broken. I first raised the issue [here](https://github.com/mdn/content/issues/8646), but I was told the entire Thunderbird tree was deleted. The link should be updated to where info about localization is.

**Comment by wsmwk** [comment]
Thanks. This is already reported as issue #263 - get-involved cites MDN for localization reference

**Comment by Parodper** [comment]
Thanks. I will close this, then.
