### ISSUE TITLE
Release notes for 91.3.1 seem not to exist

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [thundernest/thunderbird-website#279]
Just now, on Windows, I used Thunderbird's inbuild update feature to update. After installation and relaunch I opened the 'About' menu and tried to see the release notes. I saw this:

![image](https://user-images.githubusercontent.com/47056543/141810837-49a4fd10-bb70-4c2e-9da1-9ff7209a07e8.png)

**Comment by furicle** [comment]
Mostly a +1

On 91.3.0 in Windows.

Got update notice,  clicked 'Learn More'  - 91.3.1 notes don't exist.
(Haven't updated yet)

**Comment by zamunda68** [comment]
Yep, same on Mac.

**Comment by jfx2006** [comment]
They should be available now.

**Comment by LinuxOnTheDesktop** [comment]
Good stuff. Perhaps though something needs automating here - or if it is automated already, debugging.

**Comment by Sancus** [comment]
It is automated. Unfortunately, sometimes localizers break strings, which stops site rebuilds. It would be possible to work around but it rarely happens so not that big of a deal.
