### ISSUE TITLE
Unable to reset password or re-enter saved logins

### ISSUE THREAD

**Issue by lunar-regolith** [thundernest/thunderbird-website#282]
(Thunderbird 91.3.0 on Fedora 34)

I changed my password with my provider. I can now find no way to re-enter credentials for this account.

1.  The prompt that occurs when the old password is rejected at the server - allowing one to enter another, new password manually - just isn't happening anymore. "Get mail" runs at startup, then quietly fails. I just get a system-message saying Thunderbird timed out connecting to the server. "Send" produces:

> Sending of the message failed.
> The message could not be sent because connecting to Outgoing server (SMTP) [MY EMAIL PROVIDER] failed. The 
>server may be unavailable or is refusing SMTP connections. Please verify that your Outgoing server (SMTP) settings 
>are correct and try again.

There is no option I can see in Account Settings > Server Settings.

2.    I can't add or restore entries in "Saved logins" (Preferences > Privacy & Security > Passwords > Saved Passwords). I deleted the list (outgoing and incoming servers) late last night thinking they would generate again, but they aren't. I can't find any menu option to add a server to the list, never mind a password.

I have changed different settings, (e.g. SSL/TLS auth to "OAuth2", restart, then back to "normal"), trying to trigger a password prompt, but I can't get anything to work. I might have to reinstall the whole thing.

The answer is either really simple but really not easy to find or there is a failing here. Either way, this seems like a bug.

**Comment by Sancus** [comment]
support is here: https://support.mozilla.org/en-US/questions/new/thunderbird

thunderbird bug reports go here: https://bugzilla.mozilla.org/

This tracker is for issues with the website.
