### ISSUE TITLE
New release web page missing

### ISSUE THREAD

**Issue by kenakahn** [thundernest/thunderbird-website#285]
I'm running Thunderbird on Windows 10. A new release (91.5.0 64-bit) was installed. Upon opening this new release, I was taken to the following web page https://www.thunderbird.net/91.5.0/start which resulted in the message "There's nothing here". This is not the first time I've had this sequence happen after install of a new release.

**Comment by Sancus** [comment]
That's quite odd and doesn't happen normally, I don't think there is a website issue here -- that URL gets only a couple of hundred hits per week. Which implies it's somehow a misconfigured client/profile issue that only a few people have.

How old is your Thunderbird profile? What are the values for the start_page prefs? The below is what they should be on 91.5.0

![image](https://user-images.githubusercontent.com/479671/149613355-2923b176-f97b-4039-9571-ff935f4e0887.png)

**Comment by kenakahn** [comment]
Here's what my values are

![Screenshot 2022-01-15 080612](https://user-images.githubusercontent.com/31625265/149622865-296c4b89-356f-4b30-bdc5-f5177bdd196b.jpg)

Can I assume I need to at least change enabled to true and change start_page.url to what you have? Is this because I'm using an older profile? Mine is located on an external drive to make it easier to use if I need to reinstall thunderbird (e.g. new system).

**Comment by Sancus** [comment]
> Can I assume I need to at least change enabled to true and change start_page.url to what you have? Is this because I'm using an older profile? Mine is located on an external drive to make it easier to use if I need to reinstall thunderbird (e.g. new system).

Yeah, `mailnews.start_page.welcome_url` should be an empty string. That's what's causing the pageload. It should only be set on the versions where we have a whatsnew page(which is like, 1 version per year).

The others should be set the same as I have them.

What's odd is they're not bolded, bolding means set to a non-default value. I wonder if there is some file in your profile overriding the prefs. Unfortunately, very old profiles sometimes have these weird settings inconsistencies.

**Comment by kenakahn** [comment]
I set the fields to the values indicated. There was an extra keyword "mailnews.start_page.welcome_url" I set to the same value as "mailnews.start_page.url". Is this correct? Should it be something else. Should it even exist?

"Is your version from the official installer? If it is from other source, it's possible it comes with these busted settings for some reason"

The profile directory was created when I originally installed Thunderbird many years ago. To make migration easier when installing on a fresh system, I decided to move it to an external drive instead of just backing it up and copying it back to my C drive. Isn't that a valid thing to do? Is there a way to upgrade my profile to the current version without losing any information?

**Comment by Sancus** [comment]
> There was an extra keyword "mailnews.start_page.welcome_url" I set to the same value as "mailnews.start_page.url".

You should set that one to empty. It's why the page is loading on update.

> Isn't that a valid thing to do? Is there a way to upgrade my profile to the current version without losing any information?
It is a valid thing to do. That doesn't mean it's always problem free for everyone over many years :) 

It is possible to upgrade your profile, but I wouldn't try that right now. Just unset that preference and see if it resolves the problem. If you want to try exporting your data and upgrading your profile I'd ask [on the support site](https://support.mozilla.org/en-US/questions/new/thunderbird).

I'm going to close this now since it's not a website bug.

**Comment by kenakahn** [comment]
Thanks for all your help.

**Comment by Sancus** [comment]
> Thanks for all your help. If I could offer a suggestion, I'm sure I'm not the only user who has been using this software for a long time. Can I suggest (user requirement) that when the profile is changed/updated for a release (maybe just major releases) some utility/tool be provide to (automatically?) update the current profile to avoid any problems like this.

I agree, we do totally need a way to reset/clean up the profile without data loss.
