### ISSUE TITLE
USA calendar file corrupted?

### ISSUE THREAD

**Issue by jthaman** [thundernest/thunderbird-website#288]
I receive import errors when I tried to use the USA holidays ics file

https://www.thunderbird.net/media/caldata/USHolidays.ics

**Comment by jfx2006** [comment]
The file itself appears fine, and I had no issue with importing it with latest beta (98b2) using icaljs (not libical).
Closing this issue since the file is valid.

**Comment by jthaman** [comment]
I tried to import the calendar again, and encountered import error. The pop-up directed me to the error console. Here is the tail: 

```
2147500037 import-export.js:204
    putItemsIntoCal chrome://calendar/content/import-export.js:204
    AsyncFunctionThrow self-hosted:696
    handle resource:///modules/MessengerContentHandler.jsm:496
Calendar: CalDAV: Unexpected status adding item to Fastmail Calendar: 403
BEGIN:VCALENDAR

PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN

VERSION:2.0

BEGIN:VEVENT

LAST-MODIFIED:20201108T222756Z

DTSTAMP:20201115T134131Z

UID:258666554916006268

SUMMARY:New Year's Eve

RRULE:FREQ=YEARLY;COUNT=10;BYMONTHDAY=31;BYMONTH=12

CATEGORIES:Holidays

DTSTART;VALUE=DATE:20211231

DTEND:20211231T050001Z

DESCRIPTION:New Year's Eve

CLASS:PUBLIC

END:VEVENT

END:VCALENDAR

CalDavCalendar.jsm:654

```
I'm not sure how to switch between icaljs and libical in tbird.

**Comment by jfx2006** [comment]
Somehow it's trying to connect to Fastmail CALDAV. `Calendar: CalDAV: Unexpected status adding item to Fastmail Calendar: 403`

In any case, this is not a website issue. Please use the support forum. (https://support.mozilla.org/en-US/products/thunderbird). It's possible this is a Thunderbird bug, support volunteers can help determine the next steps.
