### ISSUE TITLE
Your system doesn't meet the requirements to run Thunderbird...

### ISSUE THREAD

**Issue by Gorvetco** [thundernest/thunderbird-website#294]
Yeah, I understand that Thunderbird may not be compatible with a Chromebook as Thunderbird is a desktop program. However I do already have the stable version of Thunderbird installed, thanks to having the Linux beta distribution enabled. But what bring me to writing this issue out is because I was interested in looking  into the beta channel of Thunderbird. I hadn't even proceeded to attempt to install the channel yet, just was hoping to read about it and find out more. Underneath the Logo that is promoting Thunderbird Beta it states "Your system doesn't meet the requirements to run Thunderbird" with the word "requirements" available to click to be redirected to, what i was assuming, an information page containing either more info about Thunderbird Beta, or at least the details of what devices are incompatible and which are. But upon following the redirection, I'm taken to a page with big title heading that literally says  "There's Nothing Here"... Ok. Well, so I guess because the device I'm currently using isn't compatible, F*** me then right? Apparently even though I'm interested, I don't get the chance to see more about the product (not angry or upset by the way, just giving out hard time to make light of the situation and mean no offence whatsoever
![20220402_142216](https://user-images.githubusercontent.com/102850152/161396518-277f2a6a-217f-42ad-b278-a99ba7360ee2.jpg)
![20220402_142208](https://user-images.githubusercontent.com/102850152/161396521-fc9e3243-50f7-4b52-84a2-c8cfb02d6782.jpg)
)

**Comment by Sancus** [comment]
This is fixed in https://github.com/thundernest/thunderbird.net-l10n/commit/61a4fe63ad45fed1044b5d40ca6eb11542661f0a - was a broken link for the en-CA locale. It's supposed to lead to https://www.thunderbird.net/en-US/thunderbird/99.0beta/system-requirements/

As far as Chromebooks go, yeah, not really supported. The UI for unsupported OSes may change in the future to at least offer available OS downloads.

**Comment by Gorvetco** [comment]
Thank you. Im new to git hub, so navigating my way around has so far been a learning curve
