### ISSUE TITLE
Description of Good Friday needs to be updated from Austrian Holiday calendar

### ISSUE THREAD

**Issue by prettyv** [thundernest/thunderbird-website#295]
Since 2019 Good Friday is not a public holiday anymore in Austria, but a "personal" holiday ("persönlicher Feiertag"). (see e.g. https://www.feiertage-oesterreich.at/karfreitag/)

It would be good to at least update the description to reflect this or maybe even remove the entry from the list, as the "personal" holiday is still deducted from the normal contingent of available vacation days per year. www.feiertage-oesterreich.at describes the entry like this:
```
Seit 2019 kann der Karfreitag als sog. persönlicher Feiertag aus dem Urlaubskontingent als arbeitsfreier Tag gewählt werden. Vor 2019 galt der Karfreitag als Feiertag für Angehörige der Evangelischen Kirche H. B. und A. B.\, der Altkatholischen Kirche sowie der Methodistenkirche.
```

**Comment by Sancus** [comment]
These calendars are crowd sourced, we don't maintain them ourselves, and we don't do manual fixes. 

Considering how error prone this seems to be, it's like we will be automating this in the future. See: https://github.com/thundernest/thunderbird-website/issues/298.
