### ISSUE TITLE
update beta start page

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#301]
@micahilbery and I are doing a major update of https://start.thunderbird.net/en-US/beta/

**Comment by wsmwk** [comment]
@Alecaddd, @Sancus if possible I'd like to have the new start page in place some time next week, somewhat concurent with with shipping beta 101 (but this is not a blocker). 

I sent my final text to @micahilbery, and I've asked him to sync up with you for final approvals. For reference I'm attaching his last (but not final) rendition. 

I have three remaining items 
1. should the text font size be further enlarged for greater visibility? 
2. To make the "warning" paragraph more eye catching, what do we think about having a yellow or red background?  (I don't want to scare people - but I don want them to read that, if nothing else) 
3. Micah has the "donate" section in the mockup for balance / symetry in the two column format. For the final product I'd rather not have it, as it's not helpful to beta users.  But I don't have a replacement for it.  @ryanleesipes can you think of something we can put in its place?

**Comment by Alecaddd** [comment]
> if possible I'd like to have the new start page in place some time next week, somewhat concurent with with shipping beta 101 (but this is not a blocker).

There shouldn't be any problem in adapting the HTML that Micah did to fit into the python build system. So we can set a hard deadline for this if you want. What about Wednesday hte 4th?

>     1. should the text font size be further enlarged for greater visibility?
>     2. To make the "warning" paragraph more eye catching, what do we think about having a yellow or red background?  (I don't want to scare people - but I don want them to read that, if nothing else)

I'm gonna have a little design exercise with Micah later this week as I'd like for this page to be a bit more engaging and unique. As it is right it's good, but we have a bit of time to try finding a visual language that is a bit more interesting.

>     3. Micah has the "donate" section in the mockup for balance / symetry in the two column format. For the final product I'd rather not have it, as it's not helpful to beta users.  But I don't have a replacement for it.  @ryanleesipes can you think of something we can put in its place?

Any particular reason why do you think it's not helpful for beta users?
Since we survive on donations, I think we should try to always put that call to action in a prominent position, no matter the release.

**Comment by wsmwk** [comment]
> I'm gonna have a little design exercise with Micah later this week as I'd like for this page to be a bit more engaging and unique. As it is right it's good, but we have a bit of time to try finding a visual language that is a bit more interesting.

That would be great, because more interesting and appealing is defintely one of my goals - the antithesis of a flat pane of text.

> > ```
> > 3. Micah has the "donate" section in the mockup for balance / symetry in the two column format. For the final product I'd rather not have it, as it's not helpful to beta users.  But I don't have a replacement for it.  @ryanleesipes can you think of something we can put in its place?
> > ```
> 
> Any particular reason why do you think it's not helpful for beta users? Since we survive on donations, I think we should try to always put that call to action in a prominent position, no matter the release.

Because Tom Sullivan's donation data show we get zero donations from beta users.

And so the trade off of potentially losing a few donors in favor of focusing on the core message of educating and engaging the beta user is to me very well worth it.  I discussed this with both Ryan and Lisa, who agree with this approach.

**Comment by wsmwk** [comment]
@micahilbery shared the results of the latest iteration, which is great. h

@micahilbery When do you estimate it can be made live? 

And have you all + @Sancus talked about the localization?

**Comment by wsmwk** [comment]
@thomasd8 had a question about which I got after the presentator was done ... what about reporting praise?  If we can incorporate it, great. If not, perhaps something for next round.

**Comment by wsmwk** [comment]
For the record, below are my original goals for this project of revising the "2018" version  start pages. Perhaps not everyone got to see this list, but I definitely conveyed the important bits when we started and as we iterated.  These are applicable to next steps of doing a refresh of the daily start page and the release start page. 

I am very pleased that we met several goals. (Note Item 1 "donations" is not especially applicable to beta, especially now that in beta it has been minimized to a small appeal of "Support us. Donate".  But, it will be very important for when we do the release start page.)

My biggest remaining concerns for beta are whether we have addressed item 4 (enticement) and item 5 (language).  We haven't had time to consider "language" (or culture), which would require a field survey at some later date.  I think we have at least in part hit "enticement"  with our new text, and your great work on color, icons organization, etc.  Now I am interested to hear from users.

=========

Questions / Goals / Ideas about improving the wording and design of Thunderbird Start Page:
1. Donations:
1a. How do we address complaints from users about donations on the start page? a) “every day you pester me about donations” (regardless of whether I have donated), b) “I have already donated, but you ask anyway - don’t you know that I have already donated?”
1b. How do we acknowledge/thank those who have already donated?
1c. Wording may be outdated
2. To reduce localization and maintenance requirements, we should try to use identical blocks of text for each channel. (And if a channel needs channel
specific text, add a paragraph or block of text rather than customize text, inline, to that channel) 
2a. Related - Do we want to periodically add text for special appeals? If the answer is yes:
i. How can we do that in such a way that minimizes impact to localizers?
ii. Can we have a block of text that can be turned off/on via html? For example, asking in the release channel for users to participate in
beta in our “pre-release” period. (who BTW also have their own forum? That might be an enticement. For beta users, do we dare link
to the road map?)
3. Avoid having the start page being a “wall of text”. And, how do we make it more visually appealing? Should there be more whitespace / graphics /
other ?
4. What can we add (or change) so that both new and experienced users are enticed, drawn in, and feel welcome? For example, can we provide a
reference about customizing Thunderbird through add-ons and settings, and also a pointer to learning more about TB? Maybe mirror parts of the Help
menu, or reference the items it references?
5. How do we be sensitive to language that does not match the norms of some cultures and non-en-US? (? involve someone from Japan/Korea/India,
Germany, etc. What has Fx done?)
6. Can color background be changed to more readily distinguish non-release channels? And highlight the fact that there might be danger here?
7. Is the text honest and does it align with our values?
8. Does it provide the user of that channel with all the most important information they need to know? (What are we missing?)
9. Will the text still be accurate in 2-3 years? (We don’t want to have to revise it every year)
10. Are all the major languages localized? (top 10? 20?)
11. Daily should probably closely mirror beta

**Comment by Alecaddd** [comment]
Micah started working on the code and he's gonna use the current python build system of the page so we can use l10n like we currently do.
The current objective is to have the page coded and ready for a review this Wednesday.

**Comment by Sancus** [comment]
https://start-stage.thunderbird.net/en-US/beta/

I will push the strings to l10n tomorrow, feel free to double check the page in the meantime.

**Comment by Sancus** [comment]
https://start-stage.thunderbird.net/en-US/beta/

I suppose we could localize this page now if we wanted to as well.

@wsmwk Do you have a target date for this to go live or just ASAP?

**Comment by wsmwk** [comment]
> https://start-stage.thunderbird.net/en-US/beta/

looks good to me, including all the links


> I suppose we could localize this page now if we wanted to as well. It might make beta more friendly to some.
> 
> @wsmwk Do you have a target date for this to go live or just ASAP?

Very much ASAP

**Comment by wsmwk** [comment]
> I suppose we could localize this page now if we wanted to as well. It might make beta more friendly to some.

@Sancus still very few localizations. Which means we probably need to push out #309 quick as possible so it gets to localization.

**Comment by Sancus** [comment]
> > I suppose we could localize this page now if we wanted to as well. It might make beta more friendly to some.
> 
> @Sancus we still have very few localizations. Which means we probably need to push out #309 quick as possible so it gets to localization.

95% of users use the top 10 languages(de, en-US, ja, fr, pl, it, ru, es-ES, en-GB, pt-BR, nl). We have de, en-US/GB, fr, pt-BR, nl, and missing/partials are: ja, pl, it, ru -- plus the other minor languages we have like 65% coverage.

Japanese is unfortunately almost abandoned, only one person does that since Kohei left and only once or twice a year. We probably need to appeal to some of the folks that do it for Firefox to fix that one.
