### ISSUE TITLE
feature beta download choice more prominently on thunderbird.net

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#302]
We will want issue #301 - update beta start page - to be live before the download change is made live.

**Comment by wsmwk** [comment]
Primary goals for this change are 1) substantially increase the number of beta users in the beta 101 and 102 time frame to help improve the quality of version 102 upon release, 2) better inform and engage potential beta users (via KB and other documentation changes**), 3) substantially increase the number of permanent beta users.

Currently we peak at about 40k users on beta channel.  Hoping to double that long term.  Short term, looking for at least 10-20k more users.

** related changes are issue #301, https://support.mozilla.org/en-US/kb/thunderbird-beta, update the crash reporting page, create a new debugging/troubleshooting page, provide beta users with https://support.mozilla.org/en-US/kb/new-thunderbird-102 (not yet created, but the equivalent of https://support.mozilla.org/en-US/kb/new-thunderbird-91)

**Comment by Alecaddd** [comment]
@micahilbery, how's the design work going on this?

**Comment by micahilbery** [comment]
![header](https://user-images.githubusercontent.com/10608836/165541793-6233a7e8-e6c4-4eb9-9824-ffd0a652a09b.png)
![header-1](https://user-images.githubusercontent.com/10608836/165541811-52d38085-63aa-4d59-a082-a25734f4b870.png)

**Comment by Sancus** [comment]
> ![header](https://user-images.githubusercontent.com/10608836/165541793-6233a7e8-e6c4-4eb9-9824-ffd0a652a09b.png) ![header-1](https://user-images.githubusercontent.com/10608836/165541811-52d38085-63aa-4d59-a082-a25734f4b870.png)

I'm a bit confused by this? We're not changing the *default* to Beta. The idea is to move something similar to the selector at the bottom up to the top.

I apologize in advance if you already know that and this is just a very early mockup.

**Comment by wsmwk** [comment]
When we (Ryan, Alex, me, Micah) met last week, rather than adding a top menu item for beta, the direction became adding to the current DL UI to an option to get beta, as seen in the wording "Get the beta..." in the first image.  These mockups are in iteration on that idea.

**Comment by micahilbery** [comment]
>We're not changing the *default* to Beta. The idea is to move something similar to the selector at the bottom up to the top.
> 

Correct, the idea in these screenshots is that there's a link below the download button that switches over the main header to the beta download and a link below that download button to switch back.

**Comment by Sancus** [comment]
I see. I'm not opposed to that approach, but I do think the visibility of that white text at the bottom is very low. The selector has the advantage of a highlighted tab so it's more obvious what's going on.

I'd like to see something more visible, maybe a button, maybe just bigger text somewhere else.

Also --  changing the download button should be a JS call and not a new page load, that's important. New page load adds too much friction.

**Comment by wsmwk** [comment]
I think this is an interesting iteration, and cleaner than what we had discussed. But It is more subtle than I was looking for.  I'd be in favor of make "Get beta" stand out more visually in some way, that it is a clear alternative and not just informational subtext to the download button, but not detract from the clean theme.

**Comment by Sancus** [comment]
White box looks pretty good to me, white background not so much. We can, of course, change the look of that in the future fairly easily if we don't get the results we want, I suppose.

**Comment by wsmwk** [comment]
White box outline works for me.

**Comment by Sancus** [comment]
The button does still need to say "Download Beta" though -- for accessibility reasons if nothing else.

**Comment by Alecaddd** [comment]
I would advice against using GitHub as a design review tool, is not efficient.
I will go through a review process with Micah and pull in others through Presentator.

**Comment by Sancus** [comment]
Sure, I was just trying to add some comments before this gets to the PR stage.

**Comment by wsmwk** [comment]
@Alecaddd what is next step toward putting this in production?

**Comment by wsmwk** [comment]
@Alecaddd  The DL link to be changed for this is live - https://support.mozilla.org/kb/thunderbird-beta  - so we're ready for thunderbird.net to be updated.  

@ryanleesipes This is the prerequisite for getting more beta users.

**Comment by Alecaddd** [comment]
Will sync up with Micah on Monday to get the ball rolling on this.
