### ISSUE TITLE
91.10.0 is released but release notes page is missing

### ISSUE THREAD

**Issue by rootwork** [thundernest/thunderbird-website#313]
Just updated to Thunderbird 91.10.0 via Linux Mint, but when I click on About Thunderbird > Release Notes, there's nothing there. I'm guessing it needs to be published?

Here's the full URL as passed from Thunderbird:

`https://www.thunderbird.net/en-US/thunderbird/91.10.0/releasenotes/?uri=/thunderbird/releasenotes/&locale=en-US&version=91.10.0&channel=release&os=Linux&buildid=20220525135609`

**Comment by jfx2006** [comment]
Linux Mint released too early. Thunderbird 91.10.0 is not available from official channels until May 31 (tomorrow). The notes will be made available then.
