### ISSUE TITLE
Start page errors

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#319]
@micahilbery 

102.0b6 on Windows, I'm seeing the follow in error console

23:10:34.540 Security Error: Content at https://start.thunderbird.net/media/svg/logo-wireframe-light.svg attempted to load chrome://global/locale/intl.css, but may not load external data when being used as an image.
23:10:34.541 XML Parsing Error: XML or text declaration not at start of entity
Location: https://start.thunderbird.net/media/svg/logo-wireframe-light.svg
Line Number 4, Column 1: logo-wireframe-light.svg:4:1
23:10:41.461 Security Error: Content at https://start.thunderbird.net/media/svg/logo-wireframe-light.svg attempted to load chrome://global/locale/intl.css, but may not load external data when being used as an image.
23:10:41.462 XML Parsing Error: XML or text declaration not at start of entity
Location: https://start.thunderbird.net/media/svg/logo-wireframe-light.svg
Line Number 4, Column 1:

**Comment by wsmwk** [comment]
Similar results on Mac with 102.0b8

**Comment by Sancus** [comment]
Resolved by #318.
