### ISSUE TITLE
Enable Wiki on this Repo

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#32]
@Sancus can you enable the wiki on this repo? I think that for folks like myself and new contributors it would be nice to have a place to detail where files are and what they do.

**Comment by Sancus** [comment]
OK it looks like github wikis can either be restricted to people with push access, or allowed to anyone with a github account. That's pretty lame. I unchecked the box that lets anyone with a github account edit the wiki, but I'm moderately concerned about spam. However I don't want to give push access to people just so they can edit the wiki. Kind of awkward. We'll see how it goes with unrestricted access.
