### ISSUE TITLE
header area on Thunderbird 102 What's New page is broken for German

### ISSUE THREAD

**Issue by cadeyrn** [thundernest/thunderbird-website#323]
After the update from Thunderbird 91 to Thunderbird 102 (German) a What's New page openened in the browser. The header area is a bit broken:

https://www.thunderbird.net/de/thunderbird/102.0/whatsnew/?locale=de&version=102.0&channel=release&oldversion=91.11.0

<img width="1279" alt="Bildschirmfoto 2022-07-01 um 15 42 12" src="https://user-images.githubusercontent.com/1100614/176906785-69bf9ddf-f8ec-46a6-96bb-502549997906.png">

1. There is a linked box with a heart but without any text.
2. There is another linked box below this box with an incomplete sentence.
3. Below the second box there is the rest of the text that contains a link with a blue text color on a blue background.
4. There is a stray arrow below this text.

**Comment by Sancus** [comment]
This was fixed yesterday. Thanks for the report.
