### ISSUE TITLE
Add Thunderbird YouTube link to footer

### ISSUE THREAD

**Issue by KillYourFM** [thundernest/thunderbird-website#329]
As before with the Mastodon link, we'd like to add the Thunderbird YouTube link to the site's footer / social link areas. 

URL to add: https://www.youtube.com/channel/UCuMTCmnwZPiXXVIy_TW6Bnw

Official YouTube Assets: https://www.youtube.com/howyoutubeworks/resources/brand-resources/#logos-icons-and-colors

**Comment by MelissaAutumn** [comment]
Howdy, this should be fixed as of https://github.com/thundernest/thunderbird-website/pull/337

Cheers,
Mel
