### ISSUE TITLE
lang selector shouldn't redirect to front page

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#33]
Right now the lang selector has a form with action set to redirect to front page, just because this was simplest and getting it to actually work correctly on a static site was difficult.

To function properly, it should keep you on the same page you were on when you change languages. This isn't high priority.

**Comment by ryanleesipes** [comment]
Are you aware of a good fix? Or does someone need to dream one up?

**Comment by Sancus** [comment]
There is a patch to make it fully client-side in bedrock recently that can probably be adapted to work here: https://github.com/mozilla/bedrock/pull/5582/files

**Comment by Sancus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix language selector](https://trello.com/c/DsbRBt2k/9-fix-language-selector)
