### ISSUE TITLE
Add Thunderbird LinkedIn URL to footer

### ISSUE THREAD

**Issue by KillYourFM** [thundernest/thunderbird-website#331]
Add URL to newly created Thunderbird profile page on LinkedIn. 
https://www.linkedin.com/company/thunderbird-email/

Official LinkedIn icons: https://brand.linkedin.com/content/dam/me/brand/en-us/brand-home/downloads/LinkedIn-Logos.zip

**Comment by MelissaAutumn** [comment]
Howdy, this should be fixed as of https://github.com/thundernest/thunderbird-website/pull/337

Cheers,
Mel
