### ISSUE TITLE
Download link redirects to donation page without downloading anything

### ISSUE THREAD

**Issue by wetneb** [thundernest/thunderbird-website#336]
I just tried downloading thunderbird by clicking the prominent "Free download" button on https://www.thunderbird.net/en-US/.

When doing so, I get redirected after a fairly long wait to https://give.thunderbird.net/en-US/?utm_source=thunderbird.net&utm_medium=referral&utm_content=post_download&tbdownload=true, without triggering any download in my browser (Firefox 91.13.0esr on Linux).

If I open the "Free download" link in a new tab instead, I get:
> The server at bucketlister.prod.productdelivery.prod.webservices.mozgcp.net is taking too long to respond.

I also tried without uBlock Origin and in private browsing mode, which did not solve the problem.

**Comment by Sancus** [comment]
I can't reproduce this with anything, not Firefox 91 or 108 on Windows, not Firefox 91 or 102 on Fedora, not Firefox 107 or Safari on MacOS.

Are you sure this happens with a blank profile and no add-ons installed? If so, maybe it's a distro related problem or something, not sure. It's not really possible for this to be a widespread bug or we would be drowning in reports.

Weird browser configs preventing the download are the reason the [Donation Page](https://give.thunderbird.net/en-US/?utm_source=thunderbird.net&utm_medium=referral&utm_content=post_download&tbdownload=true) has a link at the top to a direct download page, however.

**Comment by wetneb** [comment]
> I can't reproduce this with anything, not Firefox 91 or 108 on Windows, not Firefox 91 or 102 on Fedora, not Firefox 107 or Safari on MacOS.

I get the same behaviour with Chromium 105.0.5195.102, still on Linux.

> Weird browser configs preventing the download are the reason the [Donation Page](https://give.thunderbird.net/en-US/?utm_source=thunderbird.net&utm_medium=referral&utm_content=post_download&tbdownload=true) has a link at the top to a direct download page, however.

For me, that link points to https://www.thunderbird.net/download/, which resolves to https://www.thunderbird.net/en-US/download/, which has the exact same problem as https://www.thunderbird.net/en-US/.

> Are you sure this happens with a blank profile and no add-ons installed? If so, maybe it's a distro related problem or something, not sure. It's not really possible for this to be a widespread bug or we would be drowning in reports.

That's a fair point - but perhaps it would be worth making sure that the donation page actually provides a direct download link, to cater for those weird edge cases like mine?

**Comment by Sancus** [comment]
> That's a fair point - but perhaps it would be worth making sure that the donation page actually provides a direct download link, to cater for those weird edge cases like mine?

Well, it sounds to me like you're not even able to reach our download servers at all on the network level. Maybe you have a  firewall or something blocking connections. The direct download link for thunderbird 102 is https://download.mozilla.org/?product=thunderbird-102.5.0-SSL&os=win64&lang=en-US which is the same link that's on the download page.

>I get the same behaviour with Chromium 105.0.5195.102, still on Linux.

This definitely points to it being a network issue.

**Comment by wetneb** [comment]
Alright, closing then! Thanks for your time.
