### ISSUE TITLE
Change embedded mailing list signup form URL

### ISSUE THREAD

**Issue by KillYourFM** [thundernest/thunderbird-website#352]
We've merged the two existing newsletter audiences, so the existing Mailchimp Signup Form in /_includes/donate-mailing-list.html should now point to this URL as soon as possible:
[https://thunderbird.us12.list-manage.com/subscribe?u=f8051cc8637cf3ff79661f382&id=56428f2efc](https://thunderbird.us12.list-manage.com/subscribe?u=f8051cc8637cf3ff79661f382&id=56428f2efc)

The existing URL (https://mozilla.us12.list-manage.com/subscribe/post?u=f8051cc8637cf3ff79661f382&amp;id=9badb0cec2) should be removed.

**Comment by MelissaAutumn** [comment]
Maybe an earlier resolve than it should have been. Will let you know when it's live on prod.

**Comment by MelissaAutumn** [comment]
@KillYourFM it is now live.

**Comment by KillYourFM** [comment]
You rock @MelissaAutumn, thank you very much!
