### ISSUE TITLE
UTM tags for FRU donations

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#362]
We need to figure out UTM tags for FRU: https://fundraiseup.com/support/utm-parameters/

**Comment by MelissaAutumn** [comment]
Current tags are fine on our side. Will be adding two different utm_campaign for FRU vs legacy flow for our AB test:
 - donate_fru - FundraiseUp
 - donate_give - give.thunderbird.net

After the AB test these values will be removed, and any future donation after that date will be under the newly in-place platform.

**Comment by MelissaAutumn** [comment]
We'll be using the utm campaign: `donation_flow_2023`, adjust the utm medium to `fru` vs `give`. 

The rest of the tags are fine!
