### ISSUE TITLE
Design and write A/B test code

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#364]
We want to A/B test the donation flow change with FRU. I am thinking a simple 50/50 distribution for 1 week should be sufficient, and will also make the numbers easiest to understand.

**Comment by MelissaAutumn** [comment]
Do we want to keep track of what bucket they're in? (sessionStorage or localStorage) or is it okay if it's just randomly set on page load?

**Comment by Sancus** [comment]
> Do we want to keep track of what bucket they're in? (sessionStorage or localStorage) or is it okay if it's just randomly set on page load?

Nah it can be random. It doesn't matter if they go to a different page and end up in a different bucket or refresh or anything.
