### ISSUE TITLE
FRU testing

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#365]
This is for testing that FRU works and that all donation functionality is good to go before we push it live.

Testing(stage -> limited prod deployment -> full prod deployment)

(need to write a more detailed testing plan)

**Comment by MelissaAutumn** [comment]
@Sancus 
Working on the test plan, but spotted something we might want to get ahead of (I can make another ticket to track this if you'd like):

<img width="700" alt="image" src="https://user-images.githubusercontent.com/97147377/213517818-85c9719a-466f-4dd3-bf9e-f48b552369f3.png">

These footer links on the donate CTA modal are missing their final urls. 
Currently they point to:
 - Secure: Nothing?
 - Privacy Policy: https://www.mozilla.org/en-US/privacy/websites/ (Probably good)
 - Other Ways to Donate: https://give.thunderbird.net/en-CA/ways-to-give/
 - FAQ: https://give.thunderbird.net/en-CA/faq/

I suspect we'll probably just need to re-home that information somewhere on Thunderbird.net.

**Comment by MelissaAutumn** [comment]
Initial draft of a brief test plan. I need to go over the site again to make sure I have every link. (Replace the url with the staging equivalent.) 

I'd also like to look into some automated UI testing (time permitting) that would also follow (most of) the test cases below.

## Test Plan

### Test Definitions
 - Global is defined by the following links:
	 - https://www.thunderbird.net/
	 - https://www.thunderbird.net/features/
	 - https://www.thunderbird.net/get-involved/
	 - https://www.thunderbird.net/about/
	 - https://www.thunderbird.net/contact/
	 - https://www.thunderbird.net/careers/
	 - https://www.thunderbird.net/calendar/
	 - https://www.thunderbird.net/calendar/holidays/
	 - https://www.thunderbird.net/organizations/
	 - https://www.thunderbird.net/email-providers/
	 - https://www.thunderbird.net/thunderbird/all/
	 - https://www.thunderbird.net/thunderbird/releases/
	 - https://www.thunderbird.net/thunderbird/102.6.1/system-requirements/
	 - https://www.thunderbird.net/102.6.1/releasenotes/
	 - (... every other release)
- FRU donation flow is defined as the "FundraiseUp donation modal" including the following steps of the donation process:
	- "Secure Donation" screen, which includes Give Once / Monthly, and a donation amount selector
	- "Payment option" screen, including current amount, option to cover transaction fees, and various payment options.
	- "Credit card" screen, including payment inputs (you will see a test card if you're in test mode.)
	- "Personal Information" screen, allowing you to provide contact information
	- "Your mailing address" screen, allowing you to enter your mailing information.
	- "Thank you" screen, which allows you to share the donation flow link.

### Tips
 - Test Mode for the FRU donation flow can be enabled by appending `?fundraiseupLivemode=no` to the thunderbird.net url. Example: https://www.thunderbird.net/?fundraiseupLivemode=no 

### Steps
1. Ensure each donate link below triggers the FRU donation flow:
- Global
	- Header: "Donate" button
	- "Make a donation" in tiny print in the "Get Involved" section under the "Join Us" button, near the bottom of the page.
- Thunderbird.net 	
	- "Donate" button under "Thunderbird is funded by users like you", near the bottom of the page
- https://www.thunderbird.net/about/
	- "funded by donations" link in the "Our Community" section
- https://www.thunderbird.net/thunderbird/102.0/eoy/
	- "Click here to Donate!" CTA button.
- https://www.thunderbird.net/thunderbird/102.0/whatsnew/ 
	- **Note:** This page has a different UTM Campaign!
	- "Donate" button at the top
	- "Donate" button under "Thunderbird is funded by users like you", near the bottom of the page
- https://www.thunderbird.net/thunderbird/91.0/whatsnew/
	- "Donate" button at the top
	- "Donate" button under "Thunderbird is funded by users like you", near the bottom of the page
- https://www.thunderbird.net/thunderbird/78.0/whatsnew/
	- "Donate" button under "Thunderbird is funded by users like you", near the bottom of the page
- https://www.thunderbird.net/thunderbird/68.0/whatsnew/
	- "Donate" button under "Thunderbird is funded by users like you", near the bottom of the page

2. Ensure each download link below triggers the "Pay What You Want" modal, which includes a "Donate & Download" button, and a "No Thanks, Download Now" button beside it.
3. Ensure the "Donate & Download" button triggers the respective download, and launches the FRU donation flow.
4. Ensure the "No Thanks, Download now!" button triggers the respective download, and **not** the FRU donation flow.
- Global
	- The three channel releases under the tabs "Release channel", "Beta channel", and "Daily channel", near the bottom of the page
- Thunderbird.net
	- "Free Download" at the top
 - https://www.thunderbird.net/download/beta/
	 - "Download Beta" at the centre of the screen
 - https://www.thunderbird.net/about/
	 - "Free Download" under the "What is Thunderbird?" section

**Comment by MelissaAutumn** [comment]
Been running smoothly since deployment.
