### ISSUE TITLE
Create logo guidelines page

### ISSUE THREAD

**Issue by chrisilias** [thundernest/thunderbird-website#37]
The old logo guidelines were at https://www.mozilla.org/en-US/styleguide/identity/thunderbird/logo/

The latest archived version is https://web.archive.org/web/20180315075337/https://www.mozilla.org/en-US/styleguide/identity/thunderbird/logo/

Now that Thunderbird has a new logo (see https://bugzilla.mozilla.org/show_bug.cgi?id=1404648 ), there should be an updated logo guidelines page on thunderbird.net

**Comment by elioqoshi** [comment]
https://github.com/thundernest/thunderbird-website/issues/45 will fix this :)

**Comment by Sancus** [comment]
#45 should fix this as Elio stated.
