### ISSUE TITLE
Replace existing Earlybird Start Page with text informing users to migrate off Aurora channel to another channel

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#39]
Aurora is dead, and we don't plan to auto-migrate them. Users should move to beta or release channel.

We don't need the old text.  A simple, short paragraph in big bold letters with just a couple download links, with a nasty background color.   Not worth localizing IMO, but we might include the text translated in a couple of the big languages - German, Spanish, etc.

Reference https://bugzilla.mozilla.org/show_bug.cgi?id=1366893

**Comment by ryanleesipes** [comment]
I may have made this too ugly! What do you think @wsmwk?

![screenshot from 2018-11-28 12-12-06](https://user-images.githubusercontent.com/2141621/49175937-f163c100-f306-11e8-8f61-2cadfc30eee6.png)

**Comment by ryanleesipes** [comment]
Just as ugly, but now with a Beta download link!

![screenshot from 2018-11-28 12-21-02](https://user-images.githubusercontent.com/2141621/49176485-26244800-f308-11e8-8965-62a85841551c.png)
