### ISSUE TITLE
Redirect to donate page after downloading Thunderbird

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#40]
This might help us encourage some more donations.

**Comment by ryanleesipes** [comment]
Yeah, I'm hoping we can redirect to the donation page of the same language. Also @mkmelin if we could (eventually) make the donate page show a custom message like, "Thanks for downloading Thunderbird, please consider making a donation to keep the project going." when users are redirected there - that would be awesome.

**Comment by ryanleesipes** [comment]
The work has been done and it needs to be localized, you can see the PR merged here: https://github.com/mozilla/donate.mozilla.org/pull/2039

You can see the page on staging here: https://donate.mofostaging.net/en-US/thunderbird/?test=tbdownload

That end of things will hopefully be live soon and then we can do the redirect @Sancus.

**Comment by Sancus** [comment]
https://www.thunderbird.net/en-US/
https://www.thunderbird.net/fr/

This is live now for all languages, since it appeared that most of these were already localized. I could not for the life of me get a JS redirect to actually work, so new tab open it is.
