### ISSUE TITLE
Download Daily Page

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#42]
We should add this to the channel page or give it its own.

If we don't want it on either of those, we could give it an entry on the Get Involved page.

**Comment by ryanleesipes** [comment]
I actually think this is better included on "Get Involved", I don't want a user to think that daily is actually a good daily driver.

**Comment by wsmwk** [comment]
Firefox has Nightly on their https://www.mozilla.org/en-US/firefox/channel/desktop/ ... I think in an effective manner.
