### ISSUE TITLE
Thunderbird - Import Address Book not working

### ISSUE THREAD

**Issue by ghost** [thundernest/thunderbird-website#43]
I am trying to import 2 address books LDIF and the "Import" window is inactive. Only the "Cancel" button is active.
I'm using Fedora 28 Atomic Workstation.

Any solution? Tnks

**Comment by Sancus** [comment]
Sorry, this is the repository for the Thunderbird website. It isn't a support forum. 

For Thunderbird support look here: https://support.mozilla.org/en-US/questions/new/thunderbird
