### ISSUE TITLE
Nit: Change the last sentence of the in-app beta appeal

### ISSUE THREAD

**Issue by rtanglao** [thundernest/thunderbird-website#433]
**From**:

You can “Share Ideas and Feedback” and get assistance via “Get Help” or the [Beta Topicbox](https://thunderbird.topicbox.com/groups/beta) forum.

**To:**
You can find assistance via “Get Help” and “Share Ideas and Feedback” as well as the [Beta Topicbox](https://thunderbird.topicbox.com/groups/beta) forum.

**Comment by wsmwk** [comment]
I like it.
