### ISSUE TITLE
Add Thunderbird's mission statement to about page

### ISSUE THREAD

**Issue by mkmelin** [thundernest/thunderbird-website#436]
The mission statement (and preamble) should be on the about page. After much discussion the council had agreed to this wording: https://thunderbird.topicbox.com/groups/planning/T82a50212b4d24bab-M1356dbf3bfbb40b9495c02cd

**Comment by KillYourFM** [comment]
Ideal placement would be below the "Free Download" button, with "Our Mission Statement" as the heading.

**Comment by Sancus** [comment]
There's been a PR open for this for ages but it has some layout issues that need fixing https://github.com/thundernest/thunderbird-website/pull/257
