### ISSUE TITLE
Beta Release Notes Download Link Goes to Stable

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#44]
When viewing the Beta release notes on this page: https://www.thunderbird.net/en-US/thunderbird/60.0beta/releasenotes/

The download link on the right-hand side links to the front page where the download link is for the stable Thunderbird release.

Need to look into making this more discerning so it links to the correct version.

**Comment by Sancus** [comment]
Fixed in https://github.com/thundernest/thunderbird-website/commit/488c6808aca93936c6ab77641bc6f75683ed15f6 (see: https://www-stage.thunderbird.net/en-US/thunderbird/60.0beta/releasenotes/ )

Live in ~7 hours.
