### ISSUE TITLE
Update website header + footer with new Thunderbird logo

### ISSUE THREAD

**Issue by KillYourFM** [thundernest/thunderbird-website#444]
For consistency across social media and our content platforms, the website header + footers (including blog.thunderbird.net) should be updated to the new Thunderbird logo. Please reach out to the designer, Jon Hicks (jon@hicks.design) to obtain the size and format needed. Thanks!

**Comment by cadeyrn** [comment]
The new website uses new the Thunderbird logo in the header and footer. But these lines still reference the old logo:

```
<meta property="og:image" content="https://www.thunderbird.net/media/img/thunderbird/thunderbird-256.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="/media/img/thunderbird/ios-icon-180.png">
<link rel="icon" type="image/png" sizes="196x196" href="/media/img/thunderbird/favicon-196.png">
<link rel="shortcut icon" href="/media/img/thunderbird/favicon.ico">
```

**Comment by cadeyrn** [comment]
> The new website uses new the Thunderbird logo in the header and footer

To correct myself: Only the home page was changed. All sub pages still use the old branding.
