### ISSUE TITLE
Add Design Style Guide to Get Involved Page

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#45]
The style guide is available on Identihub here: https://demo.identihub.co/project/thunderbird#/

**Comment by elioqoshi** [comment]
I suspect it's better to link the full fledged style guide we are creating and Identihub more like an "assets repo". Let's figure this out once we have the photon style guide ready :)

**Comment by elioqoshi** [comment]
@Sancus here also with the (R) https://demo.identihub.co/thunderbird

**Comment by Sancus** [comment]
@elioqoshi Thanks! Opened #59 to track replacement.

**Comment by Sancus** [comment]
https://www-stage.thunderbird.net/en-US/get-involved/

The new style guide is hosted at https://style.thunderbird.net and linked on the get involved page on stage. The www.thunderbird.net changes will go live later this week.
