### ISSUE TITLE
Dependencies failure

### ISSUE THREAD

**Issue by AnXh3L0** [thundernest/thunderbird-website#46]
Hello,

As mentioned in a previous issue #31 about the new website redesign we at Ura are doing for Thunderbird, we have met some blockers along the way.

After following the steps as illustrated in the README file, I am getting errors such as:
`Can't verify hashes for these requirements because we don't have a way to hash version control repositories:`

Because of this, I can't continue building it locally to make the required changes. Can you please guide us to a solution?

System info: Thinkpad T420, Fedora 28 XFCE

**Comment by AnXh3L0** [comment]
Also, running the build script comes up with the error below:
![image](https://user-images.githubusercontent.com/25004151/41430831-6b76e77a-7011-11e8-9ed8-933f20813259.png)

**Comment by Sancus** [comment]
This should be fixed by https://github.com/thundernest/thunderbird-website/commit/e107db4db459815f9295231273815a774a40f875.

**Comment by AnXh3L0** [comment]
Hi @Sancus, the hashing error has been fixed but I still get the error when running the building script as in the screenshot above. Don't know where's the problem :(

**Comment by Sancus** [comment]
You have the wrong version of staticjinja installed. `pip uninstall staticjinja` and then re-run `pip install -r requirements.txt`. I don't know how you got the one from pypi, but you must have the one from the git URL in requirements.txt, not the one from pypi.

**Comment by AnXh3L0** [comment]
After fiddling around with the packages, I managed to fix it and built the site locally. Thanks @Sancus, closing this :)
