### ISSUE TITLE
“latest” download link still points to 102.13

### ISSUE THREAD

**Issue by sebalis** [thundernest/thunderbird-website#472]
The URL https://download.mozilla.org/?product=thunderbird-latest&os=linux64&lang=en-US (whose Windows variant is recommended in https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/latest/README.txt for retrieving the latest Thunderbird release) redirects to https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/102.13.0/linux-x86_64/en-US/thunderbird-102.13.0.tar.bz2 (and accordingly for the Windows version). I remember reading somewhere that the 102 branch will still receive a couple of updates. Is that the reason for this redirection or has it been forgotten?

**Comment by Sancus** [comment]
This isn't a website bug, see https://bugzilla.mozilla.org/show_bug.cgi?id=1843095
