### ISSUE TITLE
reduce empty space on mobile

### ISSUE THREAD

**Issue by cadeyrn** [thundernest/thunderbird-website#473]
There is way too much empty space on mobile, for example:

<img width="422" alt="Bildschirmfoto 2023-07-18 um 20 12 50" src="https://github.com/thundernest/thunderbird-website/assets/1100614/d4459012-9b6b-4682-b18e-7758989b39ba">

You should reduce the white space so that users can avoid unnecessary scrolling.

**Comment by Sancus** [comment]
Thanks. I've consolidated some of the remaining mobile issues here: https://github.com/thundernest/thunderbird-website/issues/475
