### ISSUE TITLE
for pip install -r requirements.txt, getting THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. 

### ISSUE THREAD

**Issue by mkmelin** [thundernest/thunderbird-website#48]
Trying to set up the website locally I get this:

pip install -r requirements.txt
Collecting staticjinja from https://github.com/Ceasar/staticjinja/archive/3476a3977a5dc67b24cd6a9eff874e2cfbc1d35d.tar.gz#egg=staticjinja (from -r requirements.txt (line 1))
  Downloading https://github.com/Ceasar/staticjinja/archive/3476a3977a5dc67b24cd6a9eff874e2cfbc1d35d.tar.gz
Collecting Jinja2==2.10 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting webassets==0.12.1 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/9a/35/d86c6d3bd31e2e9c8351c8766ef3688c75d56bc5233ed49061e522efc3cc/webassets-0.12.1.tar.gz
Collecting babel==2.6.0 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
Collecting webob==1.7.3 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/40/4a/893f8ee79460865f5bafb8a8fa90cbc5b099585cedbe9179c83511aab319/WebOb-1.7.3-py2.py3-none-any.whl
Collecting python-dateutil==2.6.0 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/40/8b/275015d7a9ec293cf1bbf55433258fbc9d0711890a7f6dc538bac7b86bce/python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting markdown==2.6.8 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/1d/25/3f6d2cb31ec42ca5bd3bfbea99b63892b735d76e26f20dd2dcc34ffe4f0d/Markdown-2.6.8.tar.gz
Collecting polib==1.1.0 (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/30/a2/e407c3b00cace3d7fc8df14d364deeecfeb96044e1a317de583bc26eae58/polib-1.1.0-py2.py3-none-any.whl
Collecting icalendar==3.8.3 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/f4/98/6d24c45dbeae0010d8fbe9cb9393d11b8439147e8a46d1c1c4790ff088e8/icalendar-3.8.3.tar.gz
Collecting docopt (from staticjinja->-r requirements.txt (line 1))
Collecting easywatch (from staticjinja->-r requirements.txt (line 1))
Collecting MarkupSafe>=0.23 (from Jinja2==2.10->-r requirements.txt (line 3))
Collecting pytz>=0a (from babel==2.6.0->-r requirements.txt (line 8))
Requirement already satisfied: setuptools in /home/magnus/.local/lib/python2.7/site-packages (from icalendar==3.8.3->-r requirements.txt (line 20)) (19.4)
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    docopt from https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz#sha256=49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491 (from staticjinja->-r requirements.txt (line 1))
    easywatch from https://files.pythonhosted.org/packages/0c/12/986a41d59e4d4512536b78999a21283aff5692a6c9bfb412fab7a32ecd8d/easywatch-0.0.3.tar.gz#sha256=79f4edbaef815d0b3692a12f37c95f54b33c87570b741053f6dc9531976f71d1 (from staticjinja->-r requirements.txt (line 1))
    MarkupSafe>=0.23 from https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz#sha256=a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665 (from Jinja2==2.10->-r requirements.txt (line 3))
    pytz>=0a from https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl#sha256=a061aa0a9e06881eb8b3b2b43f05b9439d6583c206d0a6c340ff72a7b6669053 (from babel==2.6.0->-r requirements.txt (line 8))
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    python-dateutil==2.6.0 from https://files.pythonhosted.org/packages/40/8b/275015d7a9ec293cf1bbf55433258fbc9d0711890a7f6dc538bac7b86bce/python_dateutil-2.6.0-py2.py3-none-any.whl#sha256=537bf2a8f8ce6f6862ad705cd68f9e405c0b5db014aa40fa29eab4335d4b1716 (from -r requirements.txt (line 13)):
        Expected sha256 1adb80e7a782c12e52ef9a8182bebeb73f1d7e24e374397af06fb4956c8dc5c0
        Expected     or 832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb
             Got        537bf2a8f8ce6f6862ad705cd68f9e405c0b5db014aa40fa29eab4335d4b1716

**Comment by clokep** [comment]
The sha256 in that line is from python-dateutil 2.7.3 (1adb80...), not 2.6.0 (537bf2a...).

**Comment by Sancus** [comment]
Sorry about that, there were a bunch of issues with this file that only happened on brand new installations. You need a hash for every dependency-of-dependencies for this to actually work on a new install, and the tools for managing this are... very bad since pipenv removed their lock -r hash output functionality.

There should be no more problems of this type.
