### ISSUE TITLE
Can't download for non-default version, system or lanugage anymore

### ISSUE THREAD

**Issue by mkmelin** [thundernest/thunderbird-website#483]
Seems there's no longer any link to https://www.thunderbird.net/en-US/thunderbird/all/ from the site. 
That was very needed, in case you need to download another version to try something out with a version not automatically guessed.

There should also be a link to https://www.thunderbird.net/en-US/thunderbird/releases/ somewhere.

**Comment by kaie** [comment]
This should be made a priority, in my opinion.

**Comment by kaie** [comment]
cc @sancus @MelissaAutumn

**Comment by kaie** [comment]
index.html shows a download button, followed by 
```
<small>{{_('Free forever.')}} <a href="{{ donate_url('header') }}">{{_('Donate')}}</a> {{_('to make it better.')}}</small>
```

which is shown as
```
Free forever.  Donate to make it better.
```

How about showing the following below that line:

```
Advanced: [Download for other languages or operating systems] or [view release notes].
```
Linking to the links that Magnus has given above.

**Comment by MelissaAutumn** [comment]
I think we should just bring back the ol'
<img width="317" alt="Three links side by side displaying the contents System & Languages, What's New, and Privacy." src="https://github.com/thundernest/thunderbird-website/assets/97147377/c5b837af-55d0-4c15-b3af-a1baa35bc627">


Any objections @micahilbery or @Sancus ?

**Comment by micahilbery** [comment]
> I think we should just bring back the ol' <img alt="Three links side by side displaying the contents System &amp; Languages, What&apos;s New, and Privacy." width="317" src="https://user-images.githubusercontent.com/97147377/273273802-c5b837af-55d0-4c15-b3af-a1baa35bc627.png">
> 
> Any objections @micahilbery or @Sancus ?

That's fine with me. Even if it's just a stopgap between now and when the full site redesign takes place.
