### ISSUE TITLE
English placeholder for newsletter form field on non-English homepage

### ISSUE THREAD

**Issue by cadeyrn** [thundernest/thunderbird-website#486]
The placeholder of the newsletter form field on the homepage is English for non-English languages like German or French.

<img width="499" alt="Bildschirmfoto 2023-08-22 um 19 46 02" src="https://github.com/thundernest/thunderbird-website/assets/1100614/1b36fa46-614c-4da6-991b-6101c0c659a1">

**Comment by MelissaAutumn** [comment]
Good catch, thanks!
