### ISSUE TITLE
Speech to text by integate "Widerporst" als KI tool?

### ISSUE THREAD

**Issue by Peter300875** [thundernest/thunderbird-website#489]
Dear all,
I'm not sure if I'm in the right forum here. If not, please let me know.

I use Peter Krueckel's software “https://pitrium.de/sprach_zu_text” to translate MP3 that I receive by email into text.
Is there a way to integrate “Widerporst” into Thunderbird so that I can see the text in the email?

Or is there already an extension to convert speech to text in thunderbird?

Best regards
Peter

**Comment by Sancus** [comment]
This is for website bugs. If you're looking for addons, you can check https://addons.thunderbird.net. If you're looking for general communication forums/channels/etc you can find them here https://www.thunderbird.net/en-US/get-involved/
