### ISSUE TITLE
https://www.thunderbird.net/ was showing 52.9.0, now showing 52.8.0. What happened?

### ISSUE THREAD

**Issue by ovari** [thundernest/thunderbird-website#50]

**Comment by Sancus** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1473893

52.9.0 was pulled because of a severe data corruption bug.

**Comment by ovari** [comment]
Thank you Sancus for the your prompt response.

If it is currently not feasible to advise the Thunderbird Flatpak maintainer directly, would it be worthwhile to send a message to tb-planning when a change of (new or reverted) stable version of Thunderbird is available on https://www.thunderbird.net? Thank you

**Comment by Sancus** [comment]
IMO you are correct that this should be communicated in some official way, perhaps it simply hasn't been yet.

@wsmwk @ryanleesipes I know the 52.9.0 pull is unusual and happened abruptly, but I can't actually find any official comms about it, whether on Twitter or tb-planning or anywhere? I'm not actually sure what the official primary source of release news is for us, to be honest. It seems like there should be something though.

**Comment by wsmwk** [comment]
I have posted to tb-planning and mozilla.support.thunderbird.  Seems to me escalating higher would be a blog post and/or twitter as you suggest.

The typical communication vechicle for "distros" is thunderbird drivers mailing list, but drivers seems like overkill for flatpak.  I am uncertain whether special mechanism is needed.

**Comment by Sancus** [comment]
Well, I'll leave that to you guys. This isn't the place to discuss comm methods anyway.
