### ISSUE TITLE
System Requirements page does not exist

### ISSUE THREAD

**Issue by agrosu1978** [thundernest/thunderbird-website#502]
Hi
Just wanted to read the [release notes](https://website-archive.mozilla.org/www.mozilla.org/thunderbird_releasenotes/en-us/thunderbird/2.0.0.0/releasenotes/) , and when I clicked the [system requirements link ](https://www.thunderbird.net/system-requirements.html)  
the page from the attached pic appear
![thunderbird_no_content](https://github.com/thundernest/thunderbird-website/assets/69220930/21c0a2fa-b33e-470e-840b-af381803e267)

**Comment by Sancus** [comment]
? Those are archived release notes from Thunderbird 2, 15 years ago. They're not meant to have fully working links, or be supported in general.

Release notes for recently released versions are here: https://www.thunderbird.net/en-US/thunderbird/releases/
