### ISSUE TITLE
Statistics don't show on addons.thunderbird.net

### ISSUE THREAD

**Issue by ovari** [thundernest/thunderbird-website#52]
Since the move from addons.mozilla.org (AMO) to addons.thunderbird.net, statistics don't show.

Screenshot below is from https://addons.thunderbird.net/en-US/thunderbird/addon/cardbook/statistics/?last=30
![Statistics for CardBook](https://user-images.githubusercontent.com/17465872/42931217-70f6100e-8b82-11e8-97e7-909d3ea5a40d.png)

Are you able to reproduce and fix?

Thank you

**Comment by Sancus** [comment]
https://github.com/thundernest/addons-server/issues/4

Mozilla uses some complex software for parsing logs, which is not part of the addons site or code. Still in the process of getting access to this, no real ETA.
