### ISSUE TITLE
{{ current_year }} missing in website footer

### ISSUE THREAD

**Issue by gion-andri** [thundernest/thunderbird-website#7]
On the website, the current year is not placed in the footer. This results in the sentence "Portions of this content are ©1998– by individual mozilla.org contributors. "

**Comment by Sancus** [comment]
Thanks, I totally missed this. Fixed in https://github.com/thundernest/thunderbird-website/commit/6d5f52b884f0f9dc870e007f7ce0fe2698e999c7

https://stage.thunderbird.net/en-US/ shows the year correctly now, although some URLs may still show it missing for a few hours due to server-side caching.
