### ISSUE TITLE
Holidays URL doesn't work without locale

### ISSUE THREAD

**Issue by chrisilias** [thundernest/thunderbird-website#78]
If I go to https://www.thunderbird.net/calendar/holidays/ , I get redirected to https://www.thunderbird.net/en-US/calendar/ .

It should fall back to https://www.thunderbird.net/en-US/calendar/holidays/

**Comment by ryanleesipes** [comment]
@Sancus any idea what is causing this? Is there a place we can explicitly set this?

**Comment by Sancus** [comment]
Fixed in https://github.com/thundernest/thundernest-ansible/commit/bf3a94905a61d64b0bd5b3bffe061ffc763f8ff2 and live now. Sorry this took so long, it was low priority and I fixed it now mainly because I was already in that file doing other things.

**Comment by chrisilias** [comment]
Thanks.
