### ISSUE TITLE
Don't store built site in git.

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#8]
We should probably just generate the website and store it on the web servers only, because commits and merging of the built files is turning into a mess.

**Comment by benbucksch** [comment]
Yes 

Am 9. August 2017 00:26:38 MESZ schrieb Andrei Hajdukewycz <notifications@github.com>:
>We should probably just generate the website and store it on the web
>servers only, because commits and merging of the built files is turning
>into a mess.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thundernest/thunderbird-website/issues/8

-- 
This email was sent from my phone.  Please excuse the brevity

**Comment by Sancus** [comment]
Turns out we do need a repo for the static files because otherwise there is really just no visibility or history for the automation or what is currently hosted on the servers without SSHing directly into them, and also, if there are ever server issues it's much easier and faster to just restore a static file checkout directly than to rebuild everything from scratch.

So we have https://github.com/thundernest/tb-website-builds now to get that stuff out of the repos where code is written, and no merges or manual commits should take place there either. People can safely ignore that repo unless they need to check out what files are actually being hosted on the servers.

**Comment by clokep** [comment]
I usually use a separate (unrelated) branch for built artifacts like this, a separate repo should work too though. 👍
