### ISSUE TITLE
Correct Style Guide link on website

### ISSUE THREAD

**Issue by marianaballa** [thundernest/thunderbird-website#83]
I noticed that when you click on the Style Guide link on the "Design" section on the "Get Involved" category, instead of being redirected to the actual Style Guide (https://thunderbird.ura.design/welcome.html) you get on the Identihub page of Thunderbird (https://demo.identihub.co/thunderbird#/). 

You might want to take a look.  :)

**Comment by Sancus** [comment]
Note that this hasn't been ignored, hosting the new Jekyll-built style guide on thunderbird.net and linking to it is on my list and may occur in the next few weeks.

**Comment by Sancus** [comment]
Fixed on stage https://www-stage.thunderbird.net/en-US/get-involved/ and will go live later this week.
