### ISSUE TITLE
Alert for new update/release should  include the 'Change Log' 

### ISSUE THREAD

**Issue by tkjtkj** [thundernest/thunderbird-website#88]
Alert for new update/release should  include the 'Change Log

This would be highly-protective, especially if update was discovererd to have a serious flaw ...

It's a thing MS should have incorporated decades ago! .. so  beat them to the punch!

**Comment by Sancus** [comment]
I don't really know what you're talking about, but this isn't the replace to report issues with Thunderbird or request features in Thunderbird. This is for the website only. You can report issues with Thunderbird on https://bugzilla.mozilla.org/
