### ISSUE TITLE
Contact page irc section has cut off sentence

### ISSUE THREAD

**Issue by mkmelin** [thundernest/thunderbird-website#89]
Following #77 in the IRC section there's a sentence cut off. It says
"You can use IRC via Thunderbird in by following "  then nothing.

**Comment by Sancus** [comment]
@ryanleesipes I can't tell what that phrase was supposed to be. It''s not present in earlier commits. Just remove it, maybe?

**Comment by ryanleesipes** [comment]
It was intended to point at a tutorial. I must have changed it last minute and it just slipped in.
