### ISSUE TITLE
Current content doesn't know how to change "Page language"

### ISSUE THREAD

**Issue by ovari** [thundernest/thunderbird-website#92]
The "Page language" changer at the bottom right of the pages has been broken for quite some time.

https://www.thunderbird.net/en-US/

For example, pick 'magyar' and the URL becomes:

https://www.thunderbird.net/en-US/?lang=hu#

not

https://www.thunderbird.net/hu/

Thank you

**Comment by ovari** [comment]
https://github.com/thundernest/thunderbird-website/issues/33

**Comment by Sancus** [comment]
This and #33 are fixed and live now.

**Comment by ovari** [comment]
Thank you @Sancus
