### ISSUE TITLE
release page layout broken by flexbox change

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#96]
I should have checked every single page before merging the flexbox PR, but most were fine... except that it seems to have broken the releases page. It's only been pushed to stage so not critically urgent.

**Comment by Sancus** [comment]
@Alecaddd see https://www-stage.thunderbird.net/en-US/thunderbird/releases/

**Comment by Alecaddd** [comment]
Ah damn, sorry about that. I assumed the main template header was globally used.
I'll check all the pages and make a PR asap.
